pkp/pkp-lib

locale/de_DE/user.xml

updated de_DE locale, re: 1afe3cf

---

classes/notification/form/NotificationMailingListForm.inc.php
classes/security/PKPRoleDAO.inc.php
classes/user/form/PKPUserForm.inc.php
controllers/grid/settings/roles/form/UserGroupForm.inc.php
js/controllers/grid/settings/roles/form/UserGroupFormHandler.js
templates/controllers/grid/settings/roles/form/userGroupForm.tpl
templates/user/userGroupSelfRegistration.tpl
templates/user/userGroups.tpl

See http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8849

*8849* Permit reader self-registration

---

classes/submission/SubmissionDAO.inc.php
controllers/grid/submissions/archivedSubmissions/ArchivedSubmissionsListGridHandler.inc.php
controllers/grid/submissions/exportableSubmissions/ExportableSubmissionsListGridHandler.inc.php

See http://pkp.sfu.ca/support/forum/viewtopic.php?f=25&t=13669#p52447

pkp/pkp-lib#316 Fix archive listing behavior for editors who are also reviewers

---

classes/core/PKPApplication.inc.php
classes/form/FormBuilderVocabulary.inc.php
classes/submission/Submission.inc.php
classes/submission/SubmissionDAO.inc.php
classes/template/PKPTemplateManager.inc.php
classes/workflow/linkAction/ExpediteSubmissionLinkAction.inc.php
controllers/modals/submissionMetadata/form/PKPSubmissionMetadataViewForm.inc.php
controllers/tab/settings/PKPDistributionSettingsTabHandler.inc.php
controllers/tab/settings/permissions/form/PermissionSettingsForm.inc.php
controllers/tab/settings/policies/form/PoliciesForm.inc.php
js/controllers/tab/settings/permissions/form/PermissionSettingsFormHandler.js
locale/en_US/common.xml
locale/en_US/manager.xml
locale/en_US/submission.xml
templates/controllers/tab/settings/permissions/form/permissionSettingsForm.tpl
templates/controllers/tab/settings/policies/form/policiesForm.tpl
tools/closure-externs.js
tools/jquery-externs.js

pkp/pkp-lib#278 Forward-port permissions improvements to OJS 3.0/OMP 1.2

---

classes/core/String.inc.php

Added epub mime type to ambiguities array in function 'mime_content_type' (file lib/pkp/classes/core/String.inc.php)

Issue355: recognize epub mime type

---

locale/de_DE/common.xml

typo fixed, cherry-picked from master

minor update to de_DE locale

---

locale/de_DE/user.xml

* fixed small, but annoying error in de_DE translation
* will cherry-pick to master and omp-dev branches

updated de_DE locale

---

locale/uk_UA/admin.xml
locale/uk_UA/common.xml
locale/uk_UA/grid.xml
locale/uk_UA/installer.xml
locale/uk_UA/manager.xml
locale/uk_UA/reader.xml
locale/uk_UA/submission.xml
locale/uk_UA/user.xml

* correct locale names and paths

updated uk_UA locale

---

templates/common/footer.tpl

S. Issue https://github.com/pkp/pkp-lib/issues/453
If necessary, please cherry-pick it also to other branches... :-)

pkp/pkp-lib#453 distinguish the different footer blocks in CSS

---

locale/de_DE/manager.xml
locale/en_US/manager.xml

Email templates can be exported as XML file and edited all at once.

pkp/pkp-lib#427 Bulk editing for email templates

---

classes/admin/form/PKPSiteSettingsForm.inc.php
classes/announcement/PKPAnnouncementDAO.inc.php
classes/announcement/PKPAnnouncementTypeDAO.inc.php
classes/controlledVocab/ControlledVocabEntryDAO.inc.php
classes/group/GroupDAO.inc.php
classes/reviewForm/ReviewFormDAO.inc.php
classes/reviewForm/ReviewFormElementDAO.inc.php
classes/security/PKPUserGroupDAO.inc.php
classes/submission/PKPAuthorDAO.inc.php
classes/user/InterestEntryDAO.inc.php
classes/user/PKPUserDAO.inc.php

pkp/pkp-lib#497 Use array_merge instead of + for merging arrays

---

controllers/api/file/PKPManageFileApiHandler.inc.php

The same as Alec's fix (s. https://github.com/pkp/pkp-lib/compare/master...asmecher:i515-fix?expand=1), but for the stable branch.

pkp/pkp-lib#515 Fix file deletion index update (1.1.1)

---

classes/context/ContextDAO.inc.php

https://github.com/pkp/pkp-lib/issues/527

pkp/pkp-lib#527 : Add in missing spaces in ContextDAO::getBySetting() SQL construction

---

styles/rtl.css

* added rtl.css from master branch
* updated rtl.css
* need this for new Arabic translation

added right-to-left css file to OJS 2

---

classes/validation/ValidatorISSN.inc.php
tests/classes/validation/ValidatorISSNTest.php

https://github.com/pkp/pkp-lib/issues/529
Cherry pick to ojs-dev, maybe ojs-stable?

pkp/pkp-lib#529 Fix ISSN Validator to properly calculate checksum for 0 and X cases.

---

classes/validation/ValidatorISSN.inc.php

It should. https://github.com/pkp/pkp-lib/issues/529#issuecomment-104331233

pkp/pkp-lib#529 Allow for X checkdigit in regexp for ISSN.

---

locale/de_DE/grid.xml
locale/de_DE/manager.xml

de_DE locale update

---

locale/ar_IQ/admin.xml
locale/ar_IQ/common.xml
locale/ar_IQ/countries.xml
locale/ar_IQ/currencies.xml
locale/ar_IQ/grid.xml
locale/ar_IQ/installer.xml
locale/ar_IQ/languages.xml
locale/ar_IQ/manager.xml
locale/ar_IQ/reader.xml
locale/ar_IQ/submission.xml
locale/ar_IQ/user.xml
plugins/citationLookup/crossref/locale/ar_IQ/locale.xml
plugins/citationLookup/isbndb/locale/ar_IQ/locale.xml
plugins/citationLookup/pubmed/locale/ar_IQ/locale.xml
plugins/citationLookup/worldcat/locale/ar_IQ/locale.xml
plugins/citationOutput/abnt/locale/ar_IQ/locale.xml
plugins/citationOutput/apa/locale/ar_IQ/locale.xml
plugins/citationOutput/mla/locale/ar_IQ/locale.xml
plugins/citationOutput/vancouver/locale/ar_IQ/locale.xml
plugins/citationParser/freecite/locale/ar_IQ/locale.xml
plugins/citationParser/paracite/locale/ar_IQ/locale.xml
plugins/citationParser/parscit/locale/ar_IQ/locale.xml
plugins/citationParser/regex/locale/ar_IQ/locale.xml
plugins/metadata/dc11/locale/ar_IQ/locale.xml
plugins/metadata/mods34/locale/ar_IQ/locale.xml
plugins/metadata/nlm30/locale/ar_IQ/locale.xml
plugins/metadata/openurl10/locale/ar_IQ/locale.xml
plugins/oaiMetadataFormats/dc/locale/ar_IQ/locale.xml

* missed those when merging a few weeks ago

updated copyright date in ar_IQ locale

---

styles/controllers/grid/grid.less
styles/pages/workflow.less

Style adjustments for the grids on editorial stage, including the new discussion grid.

Pkp/pkp lib#604 workflow editorial cleanup

---

js/controllers/form/FormHandler.js
locale/en_US/user.xml
templates/common/formErrors.tpl
templates/common/message.tpl
templates/user/login.tpl
templates/user/lostPassword.tpl
templates/user/register.tpl

Ended up with a merge commit in there somehow, but it still looks clean.

Pkp/pkp lib#639 style register and login pages

---

js/controllers/form/MultilingualInputHandler.js

Hurrah!
(I'll look into a few more things around this to see if it can be cleaned up, but not sure what progress is possible so don't let it hold up going into beta).

Fix tinymce localisation popovers

---

templates/common/frontend/header.tpl

Just doing some template structure gardening as I work through OMP stuff.

Look for search form template in frontend template dir

---

templates/common/header.tpl

PR coming for OJS which will generate `$contextSettingsUrl`. Change will be wrapped into OMP PR.

Use  in backend navigation to support OMP/OJS differences

---

styles/controllers/notification.less

Ensure pnotify panels appear above all other elements on the page

---

classes/i18n/LocaleFile.inc.php
classes/i18n/PKPLocale.inc.php

S.https://github.com/pkp/pkp-lib/issues/784
These are the changes needed for the plugin that will replace the missing translations with the English texts. The plugin is coming too.

changes needed for the replacement of missing translations with english texts

---

styles/fontawesome/icons.less
templates/common/frontend/header.tpl

Just a couple of very minor adjustments were required for the new OMP frontend.

Adjustments for new OMP frontend

---

locale/en_US/common.xml

Minor adjustment supporting [this OMP PR](https://github.com/pkp/omp/pull/149).

Add localisable string for Home in the breadcrumbs

---

js/controllers/UploaderHandler.js

Please check the comment in #789 before merging.

Fix plupload component in IE8/9

---

locale/en_US/common.xml

Companion to a PR coming for OMP.

pkp/pkp-lib#836 Add search string

---

classes/core/PKPRequest.inc.php
plugins/generic/usageStats/PKPUsageStatsLoader.inc.php
plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php
plugins/generic/usageStats/README
plugins/generic/usageStats/UsageStatsHandler.inc.php
plugins/generic/usageStats/UsageStatsOptoutBlockPlugin.inc.php
plugins/generic/usageStats/UsageStatsSettingsForm.inc.php
plugins/generic/usageStats/locale/en_US/locale.xml
plugins/generic/usageStats/templates/optoutBlock.tpl
plugins/generic/usageStats/templates/usageStatsSettingsForm.tpl

I would like to make the pull request for this branch, if someone would like to use it immediatelly...
I will then port it to master too, although the master branch seems to currently be in havy development...

data privacy option for OMP usage stats plugin

---

locale/pt_BR/admin.xml

Adds https://github.com/pkp/pkp-lib/commit/13baf96a2f7b173487fce7955d36a0ef67448557 changes.

Update Brazilian's Portuguese translation

---

locale/en_US/user.xml
templates/user/login.tpl

To be referenced by an upcoming pull request in OJS.

Allow implicit authentication to be optional

---

classes/notification/PKPNotificationManager.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/895

pkp/pkp-lib#895: Backport the ability to use "Warning" notifications

---

templates/common/frontend/footer.tpl
templates/common/frontend/header.tpl
templates/common/header.tpl

Companion PRs for OJS and OMP coming in a minute.

pkp/pkp-lib#836 Use common name for app logo so it works for any app

---

styles/controllers/grid/grid.less
templates/controllers/grid/files/filesGridFilter.tpl
templates/controllers/grid/settings/roles/userGroupsGridFilter.tpl
templates/controllers/grid/settings/user/userGridFilter.tpl
templates/controllers/grid/users/exportableUsers/userGridFilter.tpl

Hopefully that's all of them.
Old:
New:

Improve style of grid search filter panels

---

styles/helpers.less

This PR also makes some adjustments to the button styles that I felt were appropriate.

pkp/pkp-lib#923 Fix button text wrap

---

controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php
controllers/wizard/fileUpload/form/PKPSubmissionFilesUploadBaseForm.inc.php
controllers/wizard/fileUpload/form/SubmissionFilesUploadConfirmationForm.inc.php
controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php

See https://github.com/UB-Heidelberg/omp/issues/18

Fix file revision process when revision isn't wanted

---

classes/controllers/grid/feature/InfiniteScrollingFeature.inc.php
js/classes/features/InfiniteScrollingFeature.js
locale/en_US/grid.xml
styles/controllers/grid/grid.less
templates/controllers/grid/feature/infiniteScrolling.tpl

pkp/pkp-lib#955 Implement smoother loading state for infinite scroll

---

js/controllers/MenuHandler.js

Not directly related to pkp/pkp-lib#989 but included as part of some touch-ups with that issue.

Improve handling of touch events in navigation submenus

---

js/controllers/SiteHandler.js
templates/common/headerHead.tpl

Companion commits for OJS/OMP on their way.

Remove deprecated CSS/JS assets

---

classes/reviewForm/ReviewFormDAO.inc.php

Change LEFT OUTERs to EXISTS / NOT EXISTS clauses if needed; remove one unused LEFT OUTER JOIN set.  This is done to improve performance on large sets.
Resolves https://github.com/pkp/pkp-lib/issues/935

pkp/pkp-lib#935: replace multiple LEFT OUTER JOINs in Review Forms

---

styles/controllers/tab.less

Just scratching an itch with this one, really.

Replace default focus outline on tabs

---

classes/signoff/PKPSignoffDAO.inc.php

[pkp/pkp-lib#1036] Change the signoffs to the new user on merging

---

classes/announcement/PKPAnnouncementDAO.inc.php

pkp/pkp-lib#1039 Show announcements at the published date

---

classes/announcement/PKPAnnouncementDAO.inc.php

Fix previous PR regarding issue pkp/pkp-lib#1039

pkp/pkp-lib#1039 Fix 4ba8a22 - Show announcements at the published date

---

templates/common/header.tpl
templates/frontend/components/footer.tpl
templates/frontend/components/header.tpl
templates/header/usernav.tpl

This fixes a few issues brought up in #805 regarding non-context pages in a multi-context press/journal.

Fix nocontext display issues

---

styles/structure/head.less

Fix text color on tasks item in primary nav when hoevered

---

locale/pt_BR/manager.xml

cherry-picked from master branch, see https://github.com/pkp/pkp-lib/pull/920

pkp/pkp-lib#920: minor update to pt_BR locale

---

locale/pt_BR/admin.xml

This updates admin.xml locale with en_us as a base and sorts alphabetically the strings using the key name.
Please hold this open until https://github.com/pkp/pkp-lib/pull/1060 is closed (I have to know If this file needs to be sorted or not).

Update pt_br admin locale

---

locale/ar_IQ/admin.xml
locale/ar_IQ/installer.xml
locale/ar_IQ/manager.xml
locale/ar_IQ/user.xml
styles/rtl-arabic.css
styles/rtl.css

After the release of OJS ver. 2.4.7, some locale files were updated in
the English Language by adding several keys here and there, so the
Arabic version should be updated as well.
I made a brief revision to the styles used in the system, and found that
some adjustments were necessary to have a better experience to the
Arabic user. I added the (div) tag there because the right-to-left
orientation in the (body) tag wasn't enough to satisfy the required
page content view.

Updates in the Arabic locale to match those in the English version

---

templates/common/header.tpl
templates/frontend/components/footer.tpl
templates/frontend/components/header.tpl

This addresses the template part of the bug.

pkp/pkp-lib#1072 Implementing site-specific logo alt text in templates.

---

locale/ar_IQ/admin.xml
locale/ar_IQ/user.xml

**Arabic locale** updates according to updates in English locale files after OJS 2.4.7.

Adding some lines before the release of 2.4.8

---

locale/tr_TR/common.xml
locale/tr_TR/user.xml

* minor updates received by email

updated tr_TR locale

---

classes/mail/MailTemplate.inc.php
classes/task/ReviewReminder.inc.php
controllers/tab/settings/reviewStage/form/PKPReviewStageForm.inc.php
locale/en_US/manager.xml

S. https://github.com/pkp/pkp-lib/issues/562

pkp/pkp-lib#562 Implement automatic review reminders

---

controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php
locale/en_US/common.xml
locale/en_US/manager.xml
templates/controllers/tab/settings/appearance/form/journalFavicon.tpl

It seems better to be able to upload and change the journal favicon from Website Settings > Appearance

Add Journal Favicon to Website Settings > Appearance

---

classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php
classes/user/PKPUserDAO.inc.php
templates/controllers/grid/users/reviewer/form/enrollExistingReviewerForm.tpl

S. https://github.com/pkp/pkp-lib/issues/1149#issuecomment-190137165

Additional fixes from the issue 1149 

---

xml/schema/common.xml
xml/schema/submissions.xml

S. https://github.com/pkp/pkp-lib/issues/1209

pkp/pkp-lib#1209 increase the size of the URL database fields

---

templates/common/validate.tpl

Fix minify-honoring in jquery.validate

---

locale/pt_BR/admin.xml
locale/pt_BR/installer.xml
locale/pt_BR/manager.xml
locale/pt_BR/user.xml

updated pt_BR locale

---

styles/controllers/grid/grid.less
styles/controllers/grid/queries.less
styles/controllers/modal.less
styles/helpers.less
styles/linkActions.less
styles/pages/workflow.less

Visual feedback when you click on a button and tidying up some styles with the cool `&:extend(.class all)` flag that I recently learned about.

Add :active button styles and use LESS extend all flag

---

pages/reviewer/PKPReviewerHandler.inc.php

S. https://github.com/pkp/pkp-lib/issues/1178

pkp/pkp-lib#1178 fix for the Go Back button in the review wizard

---

classes/form/FormBuilderVocabulary.inc.php
templates/form/formButtons.tpl
templates/linkAction/buttonRedirectLinkAction.tpl

S. https://github.com/pkp/pkp-lib/issues/1249

pkp/pkp-lib#1249 implement the possibility to open the cancelUrl in a specific window

---

locale/ru_RU/admin.xml
locale/ru_RU/common.xml
locale/ru_RU/currencies.xml
locale/ru_RU/grid.xml
locale/ru_RU/installer.xml
locale/ru_RU/manager.xml
locale/ru_RU/reader.xml
locale/ru_RU/submission.xml
locale/ru_RU/user.xml

Various fixes and improvements

Update ru_RU locale

---

styles/controllers/grid/grid.less

See this comment: https://github.com/pkp/pkp-lib/pull/1313#discussion_r57758898

pkp/pkp-lib#1267 Move OMP-specific style out of pkp-lib

---

classes/notification/PKPNotificationManager.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/1307

pkp/pkp-lib#1307: When applicable, set the reply-to of a notification to the journal manager rather than site admin.

---

controllers/grid/users/exportableUsers/ExportableUsersGridHandler.inc.php
plugins/importexport/native/pkp-native.xsd

S. a) and e) here: https://github.com/pkp/pkp-lib/issues/1347

pkp/pkp-lib#1347 user import/export fixes

---

locale/de_DE/admin.xml
locale/de_DE/common.xml
locale/de_DE/countries.xml
locale/de_DE/editor.xml
locale/de_DE/grid.xml
locale/de_DE/installer.xml
locale/de_DE/manager.xml
locale/de_DE/reader.xml
locale/de_DE/reviewer.xml
locale/de_DE/submission.xml
locale/de_DE/user.xml

#1262 update de_DE locale

---

controllers/grid/announcements/ManageAnnouncementGridHandler.inc.php
controllers/grid/notifications/NormalNotificationsGridHandler.inc.php
controllers/grid/notifications/NotificationsGridCellProvider.inc.php
controllers/grid/notifications/NotificationsGridHandler.inc.php
controllers/grid/notifications/TaskNotificationsGridHandler.inc.php
controllers/page/PageHandler.inc.php
pages/notification/NotificationHandler.inc.php
templates/controllers/page/tasks.tpl
templates/notification/index.tpl

The announcement fix was related to the notifications (I was testing the notifications created by new announcements).

pkp/pkp-lib#993: move notifications list to grid and fix announcements listing

---

classes/citation/Citation.inc.php
classes/citation/CitationDAO.inc.php
classes/controllers/grid/citation/PKPCitationGridCellProvider.inc.php
classes/filter/CompositeFilter.inc.php
classes/filter/Filter.inc.php
classes/filter/FilterDAO.inc.php
classes/filter/FilterHelper.inc.php
classes/metadata/MetadataDescription.inc.php
classes/metadata/MetadataDescriptionDAO.inc.php
classes/submission/Representation.inc.php
plugins/citationParser/paracite/filter/ParaciteRawCitationNlm30CitationSchemaFilter.inc.php
plugins/importexport/native/filter/NativeXmlRepresentationFilter.inc.php
plugins/importexport/native/filter/RepresentationNativeXmlFilter.inc.php
plugins/metadata/nlm30/tests/filter/Nlm30Nlm23CrosswalkFilterTest.php
plugins/metadata/nlm30/tests/filter/PKPSubmissionNlm30XmlFilterTest.php
tests/classes/citation/CitationDAOTest.php
tests/classes/filter/FilterDAOTest.php
tests/classes/filter/FilterHelperTest.php
tests/classes/filter/FilterTest.php
tests/classes/metadata/MetadataDescriptionDAOTest.php

Addresses pkp/pkp-lib#1342 by normalizing usage throughout all `DataObject` subclasses.

pkp/pkp-lib#1342 standardizes all DataObject subclasses on getSequence()/setSequence()

---

styles/controllers/grid/grid.less

No issue attached to this. Something I've been meaning to fix for a while.

Fix font assignment in grid search control

---

classes/core/PKPRequest.inc.php
classes/plugins/ThemePlugin.inc.php
controllers/page/PageHandler.inc.php

@beghelli, do you mind reviewing this one?

pkp/pkp-lib#1391 Permit protocol-relative URLs in compiled CSS

---

classes/i18n/PKPLocale.inc.php

S. https://github.com/pkp/pkp-lib/issues/1031

pkp/pkp-lib#1031 synchronize timezone setting with PHP and DB

---

plugins/citationLookup/crossref/tests/filter/CrossrefNlm30CitationSchemaFilterTest.php

The tested DOI changed the URL, thus the tests are failing...
S. https://travis-ci.org/pkp/ojs/jobs/130581448 and https://github.com/pkp/ojs/pull/839#issuecomment-219463779

Crossref citation lookup test fix

---

locale/it_IT/admin.xml
locale/it_IT/common.xml
locale/it_IT/countries.xml
locale/it_IT/currencies.xml
locale/it_IT/default.xml
locale/it_IT/editor.xml
locale/it_IT/grid.xml
locale/it_IT/installer.xml
locale/it_IT/manager.xml
locale/it_IT/reader.xml
locale/it_IT/reviewer.xml
locale/it_IT/submission.xml
locale/it_IT/user.xml

* preparation for new it_IT translation work

updated it_IT locale

---

classes/plugins/PKPPubIdPlugin.inc.php
classes/plugins/PKPPubIdPluginDAO.inc.php
classes/plugins/PKPPubIdPluginHelper.inc.php
classes/submission/PKPSubmissionFileDAO.inc.php
classes/submission/Submission.inc.php
classes/submission/SubmissionDAO.inc.php
classes/submission/SubmissionFile.inc.php
classes/submission/SubmissionFileDAODelegate.inc.php
controllers/api/file/PKPManageFileApiHandler.inc.php
controllers/grid/pubIds/form/PKPAssignPublicIdentifiersForm.inc.php
controllers/grid/representations/RepresentationsGridCellProvider.inc.php
controllers/grid/representations/RepresentationsGridHandler.inc.php
controllers/tab/pubIds/form/PKPPublicIdentifiersForm.inc.php
locale/en_US/submission.xml
plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php
templates/controllers/api/file/editMetadata.tpl

S. https://github.com/pkp/pkp-lib/issues/1457 a), b), c), d) and e)

New pub ids

---

classes/security/authorization/DataObjectRequiredPolicy.inc.php

S. https://github.com/pkp/ojs/pull/870#discussion_r67882351

change is_numeric to ctype_digit

---

classes/mail/Mail.inc.php

pkp/pkp-lib#1596: Check if $replyTo is array before passing it to array_key_exists

---

locale/ca_ES/user.xml
locale/de_DE/user.xml
locale/en_US/user.xml
locale/es_ES/user.xml

`user.login.activated` was a duplicate in user.xml, removed from all locales that had inherited the duplication

removed duplicate key in locale files

---

locale/es_ES/admin.xml

cherry-picked from #1589 for ojs-stable-2_4_8

es_ES locale update

---

locale/fr_CA/admin.xml

fr_CA locale update  cherry-picked from `ojs-dev-2_4` branch

fr_CA locale update

---

styles/form/form.less

S. h) here: https://github.com/pkp/pkp-lib/issues/1457

pkp/pkp-lib#1457 UI fixes

---

locale/pt_PT/admin.xml
locale/pt_PT/common.xml
locale/pt_PT/grid.xml
locale/pt_PT/installer.xml
locale/pt_PT/languages.xml
locale/pt_PT/manager.xml
locale/pt_PT/reader.xml
locale/pt_PT/submission.xml
locale/pt_PT/user.xml

Another update by José Castro Silva
@asmecher , how do you feel about the languages file? It's not translated...
#1560

pt_PT locale: updated locale files

---

classes/session/Session.inc.php

pkp/pkp-lib#1654: defining $algos

---

classes/context/Context.inc.php
classes/core/DataObject.inc.php
classes/plugins/PKPPubIdPlugin.inc.php
classes/plugins/PKPPubIdPluginHelper.inc.php
classes/submission/Representation.inc.php
classes/submission/Submission.inc.php
classes/submission/SubmissionFile.inc.php
styles/pages/workflow.less

according to the code review comments...

add getDAO to DataObject

---

templates/controllers/grid/settings/roles/form/userGroupForm.tpl
templates/controllers/grid/users/author/form/authorForm.tpl

Move the required fields indicator above buttons in modal forms

---

classes/submission/PKPSubmissionFileDAO.inc.php
classes/submission/SubmissionArtworkFile.inc.php
classes/submission/SubmissionFile.inc.php
classes/submission/SubmissionFileDAODelegate.inc.php
classes/template/PKPTemplateManager.inc.php

S. https://github.com/pkp/pkp-lib/issues/1694

pkp/pkp-lib#1694 move chapterId to SubmissionFile

---

classes/tombstone/DataObjectTombstoneSettingsDAO.inc.php

fix undefined locale index notice

---

locale/de_DE/grid.xml

* following the suggestion in #1509 (thanks @henkela for spotting this)

fixed wrong translation in de_DE locale

---

locale/de_DE/admin.xml
locale/de_DE/common.xml
locale/de_DE/editor.xml
locale/de_DE/grid.xml
locale/de_DE/manager.xml
locale/de_DE/submission.xml
plugins/generic/usageStats/locale/de_DE/locale.xml

#1582 
last updates to de_DE locale before the release of OJS 3.0

last updates to de_DE locale

---

xml/schema/metrics.xml

S. http://forum.pkp.sfu.ca/t/ojs-upgrade-failed-2-4-8-1-to-3-0-0/20226/7

define column metric as integer instead of small integer

---

classes/plugins/PluginHelper.inc.php

This refactors temporary file moving to it's own function and improves temporary file deletion.

Refactor temporary file moving in PluginHelper.

---

templates/submission/submissionMetadataFormFields.tpl

https://github.com/pkp/pkp-lib/issues/1854

fix for #1854

---

classes/controllers/grid/plugins/PluginGridHandler.inc.php
classes/plugins/PluginHelper.inc.php
controllers/grid/plugins/form/UploadPluginForm.inc.php
templates/controllers/grid/plugins/form/uploadPluginForm.tpl

S. https://github.com/pkp/pkp-lib/issues/1872

pkp/pkp-lib#1872 UI plugin upgrade fix

---

classes/controllers/grid/plugins/PluginGridHandler.inc.php
classes/plugins/PluginHelper.inc.php
controllers/grid/plugins/form/UploadPluginForm.inc.php
templates/controllers/grid/plugins/form/uploadPluginForm.tpl

s. https://github.com/pkp/pkp-lib/issues/1872
cherry-pick from master...

1872 stable3

---

classes/template/PKPTemplateManager.inc.php

@asmecher This stores unique template files for each context (+ a set for the overall site context). I'm wondering now if I should do it per theme instead. Thoughts?

pkp/pkp-lib#1862 Compile unique template files for each context

---

classes/plugins/ImportExportPlugin.inc.php
plugins/importexport/users/PKPUserImportExportPlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/1709
this is a cherry-pick to ojs-stable-3_0_0

pkp/pkp-lib#1709 provide export XML for download

---

js/classes/Helper.js

s. https://github.com/pkp/pkp-lib/pull/1945#issuecomment-257985786
s. https://github.com/pkp/pkp-lib/issues/1792

ImportExport js object added to Helper

---

classes/core/PKPComponentRouter.inc.php

pkp/pkp-lib#1973: Correct description of file mapping for $$$call$$$'s path/to/component

---

classes/core/PKPComponentRouter.inc.php

pkp/pkp-lib#1973: note that component handlers could be found under any "controllers" folder.

---

templates/controllers/tab/settings/appearance/form/favicon.tpl
templates/controllers/tab/settings/appearance/form/homepageImage.tpl
templates/controllers/tab/settings/appearance/form/stylesheet.tpl

pkp/pkp-lib#1976 Add missing delimiters to controllers/tab/settings/appearance/form templates.

---

classes/cliTool/ScheduledTaskTool.inc.php
plugins/generic/acron/PKPAcronPlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/1905
This is cherry-pick to master branch...

pkp/pkp-lib#1905 A more reliable semaphore for Acron Plugin

---

tests/plugins/citationLookup/pubmed/filter/PubmedNlm30CitationSchemaFilterTest.php

s. https://github.com/pkp/pkp-lib/issues/1959
This is a cherry-pick to ojs-dev-2_4

pkp/pkp-lib#1958 Disable PubMed web API tests for TLS auth problem

---

js/controllers/form/FileUploadFormHandler.js

s. https://github.com/pkp/pkp-lib/commit/ba33ba73659b2fd3ee825cd9028db13994e25614#commitcomment-19942314
needed for a JS file in QuickSubmit plugin -- for cover images...

make file upload preview variable protected

---

classes/submission/Submission.inc.php
tests/classes/submission/SubmissionTest.inc.php

This allows for improved page range handling (e.g. first page and last page, first and last page of first contiguous range, etc.)
Basis for resolving pkp/pkp-lib#333.

Parse submission pages into an array

---

plugins/importexport/native/filter/NativeExportFilter.inc.php
plugins/importexport/native/filter/PKPAuthorNativeXmlFilter.inc.php
plugins/importexport/native/filter/RepresentationNativeXmlFilter.inc.php
plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php
plugins/importexport/users/filter/PKPUserUserXmlFilter.inc.php
plugins/importexport/users/filter/UserGroupNativeXmlFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/2074

pkp/pkp-lib#2074: Update use of createElement and createElementNS

---

classes/plugins/BlockPlugin.inc.php
classes/plugins/GatewayPlugin.inc.php
classes/plugins/LazyLoadPlugin.inc.php
classes/plugins/Plugin.inc.php
controllers/listbuilder/admin/siteSetup/AdminBlockPluginsListbuilderHandler.inc.php
controllers/listbuilder/settings/BlockPluginsListbuilderHandler.inc.php
controllers/tab/settings/siteSetup/form/SiteSetupForm.inc.php
templates/controllers/tab/settings/appearance/form/sidebar.tpl

s. https://github.com/pkp/pkp-lib/pull/1988
from issue: https://github.com/pkp/pkp-lib/issues/1859

I1859 sitewide sidebar

---

classes/plugins/ImportExportPlugin.inc.php
plugins/importexport/native/filter/PKPAuthorNativeXmlFilter.inc.php
plugins/importexport/native/filter/RepresentationNativeXmlFilter.inc.php
plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/2117

pkp/pkp-lib#2117 Display native export validation errors

---

plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/2138

pkp/pkp-lib#2138 Use %Y-%m-%d instead of %F in strftime

---

classes/submission/Submission.inc.php
tests/classes/submission/SubmissionTest.php

Helps to forward port pkp/pkp-lib#333 to master and provides foundation for resolving pkp/pkp-lib#2076.
Both issues still need application-specific pull requests for full resolution.

pkp/pkp-lib#333, pkp/pkp-lib#2076: forward port Submission::getPageArray() to master.

---

tests/classes/submission/SubmissionTest.php

This is just a temporary fix for the submission test, till a better solution is not found...

pkp/pkp-lib#333, pkp/pkp-lib#2076: temporary fix the submission test

---

locale/pt_BR/manager.xml

Translation of "manager.setup.layout.sidebar"

Translation of tag to pt_BR

---

styles/pages/workflow.less

s. https://github.com/pkp/pkp-lib/issues/850

doaj buttons css

---

js/controllers/form/FileUploadFormHandler.js

s. https://github.com/pkp/pkp-lib/issues/2083

pkp/pkp-lib#2083 consider readOnly for cover image upload

---

locale/cs_CZ/admin.xml
locale/cs_CZ/installer.xml
locale/cs_CZ/languages.xml
locale/cs_CZ/manager.xml
locale/cs_CZ/user.xml
plugins/metadata/dc11/locale/cs_CZ/locale.xml

Update from our translator Jiří Dlouhý

updated OJS2 locale: cs_CZ

---

classes/submission/Submission.inc.php
classes/submission/SubmissionDAO.inc.php
classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php
plugins/importexport/native/filter/NativeXmlSubmissionFilter.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php
plugins/importexport/native/pkp-native.xsd

s. https://github.com/pkp/pkp-lib/issues/1873

migrate comments for the editor

---

classes/xslt/XMLTypeDescription.inc.php
plugins/importexport/native/filter/NativeExportFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/1955

pkp/pkp-lib#1955 no XML validation option for the export plugins

---

locale/ar_IQ/common.xml
locale/ar_IQ/countries.xml
locale/ar_IQ/currencies.xml
locale/ar_IQ/grid.xml
locale/ar_IQ/languages.xml
locale/ar_IQ/reviewer.xml
locale/ar_IQ/submission.xml
locale/ar_IQ/user.xml

Some minor updates related to Arabic language files

Updating PKP-Lib repo after the release of OJS 3.0.2 for Arabic locale

---

classes/plugins/importexport/PKPImportExportDeployment.inc.php
plugins/importexport/native/PKPNativeImportExportDeployment.inc.php
plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php

s. b1), b2) and b3) here: https://github.com/pkp/pkp-lib/issues/1709

pkp/pkp-lib#1709 consider query files and source attribute, and use the same file id for all revisions imports

---

classes/user/PKPUserDAO.inc.php

Change double quotes to single quotes in SQL query for Postgres

---

classes/mail/MailTemplate.inc.php
classes/task/ReviewReminder.inc.php

this is the cherry-pick to ojs-stable-3_0_2

Fix context in reminders sent using Acron

---

classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php
classes/submission/reviewAssignment/ReviewAssignment.inc.php
classes/submission/reviewAssignment/ReviewAssignmentDAO.inc.php
classes/submission/reviewRound/ReviewRoundDAO.inc.php
classes/submission/reviewer/form/ReviewerReviewStep3Form.inc.php
classes/user/PKPUserDAO.inc.php
controllers/grid/users/reviewer/form/ReviewerForm.inc.php
controllers/modals/editorDecision/form/EditorDecisionWithEmailForm.inc.php
xml/schema/reviews.xml

s. 3) here: https://github.com/pkp/pkp-lib/issues/2173

pkp/pkp-lib#2173 (3) remove review assignment cancel function

---

plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/2256

pkp/pkp-lib#2265 fix import of review_interests

---

classes/file/FileManager.inc.php

s. https://github.com/pkp/pkp-lib/issues/2003

pkp/pkp-lib#2003 consider TAR GZ as extension for the server file name

---

controllers/grid/submissions/SubmissionsListGridCellProvider.inc.php

Details here: https://github.com/pkp/pkp-lib/issues/2383

Use the correct user id in getUrlByUserRoles / getLastReviewRoundReviewAssignmentByReviewer

---

classes/task/ReviewReminder.inc.php

Fix the one clic access link in automatically sent reviews: https://github.com/pkp/pkp-lib/issues/2412

Add reviewId to oneclick link in automatic review reminders

---

classes/form/FormBuilderVocabulary.inc.php

Desrcription here: https://github.com/pkp/pkp-lib/issues/2418

consider required param for textareas

---

controllers/grid/users/reviewer/form/ReviewReminderForm.inc.php
controllers/grid/users/reviewer/form/ReviewerForm.inc.php

Explained here: https://github.com/pkp/pkp-lib/issues/2410
@asmecher, the `initdata` part maybe needs some revising, but this is working already as is.

Check for oneclick access in manual review reminders

---

classes/controllers/grid/GridHandler.inc.php
classes/controllers/grid/GridRow.inc.php

Mostly making parameter ordering and typing consistent.

pkp/pkp-lib#2449: correct method documentation for GridRow and GridHandler

---

styles/form/form.less

See http://forum.pkp.sfu.ca/t/ojs-tagit-autocomplete-suggestions-pulldown-width/30615

Increase the width of the autocomplete dropdown

---

plugins/importexport/native/filter/NativeXmlSubmissionFilter.inc.php
plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php
plugins/importexport/native/pkp-native.xsd

Resolves pkp/pkp-lib#2142 for the suggestion of adding License and Copyright information.

pkp/pkp-lib#2142: Enable native import/export of LicenseUrl and Copyright Holder/Year.

---

classes/template/PKPTemplateManager.inc.php

s. https://github.com/pkp/pkp-lib/commit/febd59fad1ceb906c784ca841af73b3352619462#commitcomment-21984709

fix template display hook

---

classes/plugins/AuthPlugin.inc.php
classes/security/AuthSource.inc.php

pkp/pkp-lib#2443: moving AuthPlugin to pkp-lib

---

plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php
plugins/importexport/native/pkp-native.xsd

Resolves pkp/pkp-lib#2142 for the suggestions of optional elements being derived from known information.

pkp/pkp-lib#2142: Allow Native XML import to autodetect uploader and filesize for submission file revisions

---

locale/ar_IQ/editor.xml
locale/ar_IQ/manager.xml
locale/ar_IQ/submission.xml

Updating some Arabic locale files

---

controllers/grid/files/copyedit/ManageCopyeditFilesGridHandler.inc.php
controllers/grid/queries/QueriesGridHandler.inc.php
controllers/grid/users/stageParticipant/StageParticipantGridHandler.inc.php
controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php

s. https://github.com/pkp/pkp-lib/issues/2519

pkp/pkp-lib#2519 fix notifications in a pre-review discussion

---

classes/plugins/importexport/PKPImportExportDeployment.inc.php
plugins/importexport/native/filter/NativeImportFilter.inc.php

There may be constraints which legitimately prevent adding a submission via the DAO, so test to see whether an object is added before acting on it.
Helps resolve pkp/pkp-lib#2461.

pkp/pkp-lib#2461: Do not assume the Native Import can successfully create an object in the database

---

classes/security/authorization/SubmissionAccessPolicy.inc.php
classes/security/authorization/internal/ReviewAssignmentAccessPolicy.inc.php
controllers/grid/files/review/ReviewerReviewFilesGridDataProvider.inc.php
templates/reviewer/review/step1.tpl

s. https://github.com/pkp/pkp-lib/issues/2481

pkp/pkp-lib#2481 Fix reviewer access to declined submissions

---

classes/oai/PKPOAIDAO.inc.php

See: http://forum.pkp.sfu.ca/t/ojs2-oaipmh-and-getearliestdatestamp-ojs-2-4-8/31326

getEarliestDatestamp gets really earliest now

---

classes/core/PKPComponentRouter.inc.php

s. https://github.com/pkp/pkp-lib/issues/2572

pkp/pkp-lib#2572 add operation to the LoadComponentHandler hook

---

classes/oai/PKPOAIDAO.inc.php

s. https://github.com/pkp/pkp-lib/issues/2566

pkp/pkp-lib#2566 OAI fixes

---

tools/installPluginVersion.php

s. https://github.com/pkp/pkp-lib/issues/2503
This considers also other plugin installation functions...

pkp/pkp-lib#2503 Add a tool to permit easy installation of plugins

---

locale/fr_CA/admin.xml
locale/fr_CA/common.xml
locale/fr_CA/editor.xml
locale/fr_CA/manager.xml
locale/fr_CA/submission.xml
locale/fr_CA/user.xml

-admin.xml: adding key admin.settings.oaiRegistration
-common.xml: adding key common.downloadPdf
-editor.xml: some misspelling, wording; adding key
editor.publicIdentificationExistsForTheSameType
-manager.xml: some misspelling, wording
-submission.xml: adding doubel-quotes
-user.xml: adding key user.login.rememberUsernameAndPassword

pkp/pkp-lib#2602 Small modifications for version 3.1

---

locale/pt_BR/user.xml

This PR adds a missing translation and fixes some incorrect translations for pt_BR locale.

Update locale user.xml pt_BR

---

locale/en_US/manager.xml
plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php

pkp/pkp-lib#2650: Check for duplicate submission file revision before insert via native import

---

classes/form/validation/FormValidatorReCaptcha.inc.php
classes/notification/form/NotificationMailingListForm.inc.php
lib/recaptcha/recaptchalib.inc.php

Resolves pkp/pkp-lib#2608; requires OJS PR.

pkp/pkp-lib#2608: Enable ReCAPTCHA v2 as an option

---

classes/plugins/LazyLoadPlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/2699

pkp/pkp-lib#2699 consider site plugins in get/setEnabled

---

plugins/importexport/native/filter/NativeXmlPKPAuthorFilter.inc.php
plugins/importexport/native/filter/PKPAuthorNativeXmlFilter.inc.php
plugins/importexport/native/pkp-native.xsd
plugins/importexport/users/filter/PKPUserUserXmlFilter.inc.php
plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/1896

pkp/pkp-lib#1896 add orcid to native and user import/export

---

classes/services/queryBuilders/BaseQueryBuilder.inc.php

default collation #2163

---

locale/es_ES/admin.xml
locale/es_ES/common.xml
locale/es_ES/editor.xml
locale/es_ES/manager.xml
locale/es_ES/submission.xml
plugins/citationLookup/crossref/locale/es_ES/locale.xml
plugins/citationLookup/pubmed/locale/es_ES/locale.xml
plugins/citationLookup/worldcat/locale/es_ES/locale.xml
plugins/citationOutput/abnt/locale/es_ES/locale.xml
plugins/citationOutput/apa/locale/es_ES/locale.xml
plugins/citationOutput/mla/locale/es_ES/locale.xml
plugins/citationOutput/vancouver/locale/es_ES/locale.xml
plugins/citationParser/freecite/locale/es_ES/locale.xml
plugins/citationParser/paracite/locale/es_ES/locale.xml
plugins/citationParser/parscit/locale/es_ES/locale.xml
plugins/citationParser/regex/locale/es_ES/locale.xml
plugins/generic/acron/locale/es_ES/locale.xml
plugins/generic/usageStats/locale/es_ES/locale.xml

received files from translators for #2725
see https://pkp.sfu.ca/wiki/index.php?title=OJS:_Spanish_(es_ES)

#2725 es_ES locale update

---

classes/submission/action/EditorAction.inc.php

s. https://github.com/pkp/pkp-lib/issues/2673

pkp/pkp-lib#2673 replace notification variable reviewerName

---

classes/submission/action/EditorAction.inc.php
controllers/grid/files/attachment/EditorSelectableReviewAttachmentsGridHandler.inc.php
controllers/grid/files/copyedit/SelectableCopyeditFilesGridHandler.inc.php
controllers/grid/files/final/SelectableFinalDraftFilesGridHandler.inc.php
controllers/modals/editorDecision/form/SendReviewsForm.inc.php
js/controllers/modals/editorDecision/form/EditorDecisionFormHandler.js
locale/en_US/editor.xml
locale/en_US/submission.xml
pages/workflow/PKPWorkflowHandler.inc.php
templates/controllers/modals/editorDecision/form/promoteForm.tpl
templates/controllers/modals/editorDecision/form/recommendationForm.tpl
templates/controllers/modals/editorDecision/form/sendReviewsForm.tpl
tools/jquery-externs.js

rebase from https://github.com/pkp/pkp-lib/pull/2733 in order to be able to merge...

pkp/pkp-lib#1144 and pkp/pkp-lib#1258 Editor decision forms

---

controllers/grid/announcements/form/AnnouncementForm.inc.php
locale/en_US/common.xml
templates/controllers/grid/announcements/form/announcementForm.tpl

First fix for https://github.com/pkp/pkp-lib/issues/2561

Make sending an announcement notification optional

---

classes/notification/managerDelegate/review/ReviewRoundNotificationManager.inc.php

s. https://github.com/pkp/pkp-lib/issues/2806

pkp/pkp-lib#2806 fix notification URL in ReviewRoundNotificationManager

---

styles/controllers/grid/grid.less

And this one too, thanks @bozana  (see https://github.com/pkp/ojs/pull/1548)

Minor fixes for the submission lists and ui-library integration

---

locale/it_IT/admin.xml
locale/it_IT/installer.xml
locale/it_IT/manager.xml
locale/it_IT/user.xml

This is the update of pkp-lib locale for it_IT.
It is about version 2.4.8

Update of it_IT in pkp-lib, version 2.4.8

---

locale/it_IT/admin.xml
locale/it_IT/installer.xml
locale/it_IT/manager.xml
locale/it_IT/user.xml

cherry-picked from ojs-stable-2_4_8

it_IT locale update

---

classes/core/PKPRequest.inc.php
classes/handler/APIHandler.inc.php
classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php
classes/user/form/APIProfileForm.inc.php
composer.json
composer.lock
locale/en_US/user.xml

This is the JSON Web Tokens code written during the sprint. It doesn't do much, but it's a start for using patterns based on JWT for API security. @asmecher @kaschioudi

add initial JWT support to API

---

locale/fr_CA/submission.xml

Added submission.authorBiography and submission.authorWithAffiliation for fr_CA

French translations for submission display

---

locale/es_ES/submission.xml

some minor errors and I changed "Fichero" by "Archivo"  (in all OJS is used "archivo" but some cases need change this word)

minor update to submission.xml

---

styles/form/form.less

@bozana can you try this and see if it works?

Fix tag-it field height when empty and in read-only mode

---

locale/de_DE/api.xml

Add api.xml for de_DE locale

---

locale/de_DE/admin.xml

Add missing translation to de_DE/admin.xml

---

locale/pt_BR/user.xml

propose translation of 5 messages and move user.login.rememberUsernameAndPassword to user.login group

translate user.apiKey messages to pt_BR

---

locale/de_DE/editor.xml

minor de_DE locale update

---

classes/form/FormBuilderVocabulary.inc.php
classes/services/entityProperties/PKPBaseEntityPropertyService.inc.php

Fix string concatenation (found by PhpStorm)

---

js/functions/citation.js
js/lib/jquery/plugins/jquery.pkp.js
plugins/generic/usageStats/js/UsageStatsGraphHandler.js
tools/closure-externs-check-only.js
tools/closure-externs.js
tools/jquery-externs.js

PhpStorm added some missing semicolons and removed wrong semicolons.

Clean code with PhpStorm

---

classes/security/UserGroupDAO.inc.php

s. https://github.com/pkp/pkp-lib/issues/2980

pkp/pkp-lib#2980 order by user_group_id

---

classes/services/PKPNavigationMenuService.inc.php
templates/common/header.tpl
templates/header/usernav.tpl

s. https://github.com/pkp/pkp-lib/issues/2967

pkp/pkp-lib#2967 Administration link if only one context exists

---

controllers/listbuilder/files/FilesListbuilderHandler.inc.php

used here: https://github.com/pkp/omp/blob/master/controllers/listbuilder/files/ChapterFilesListbuilderHandler.inc.php#L18

add FileListbuilderGridCellProvider used in OMP

---

classes/services/PKPNavigationMenuService.inc.php
locale/ar_IQ/manager.xml
locale/ca_ES/manager.xml
locale/cs_CZ/manager.xml
locale/da_DK/manager.xml
locale/de_DE/manager.xml
locale/en_US/manager.xml
locale/es_ES/manager.xml
locale/eu_ES/manager.xml
locale/fi_FI/manager.xml
locale/fr_CA/manager.xml
locale/fr_FR/manager.xml
locale/id_ID/grid.xml
locale/it_IT/manager.xml
locale/nb_NO/manager.xml
locale/nl_NL/manager.xml
locale/pl_PL/manager.xml
locale/pt_BR/manager.xml
locale/pt_PT/manager.xml
locale/ru_RU/manager.xml
locale/sr_RS@cyrillic/manager.xml
locale/sr_RS@latin/manager.xml
locale/sv_SE/manager.xml
locale/tr_TR/manager.xml
locale/uk_UA/manager.xml
locale/zh_CN/manager.xml
templates/frontend/pages/editorialTeam.tpl

s. https://github.com/pkp/pkp-lib/issues/2441

pkp/pkp-lib#2441 rename the context setting masthead into editorialTeam 

---

classes/template/PKPTemplateManager.inc.php
pages/admin/AdminHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/3009

pkp/pkp-lib#3009 always provide multipleContexts variable

---

locale/sv_SE/grid.xml
locale/sv_SE/manager.xml
locale/sv_SE/user.xml

Hi! Please find a few corrections and additions to the sv_SE locale. Cherry-picking to 3.1 is greatly appreciated if possible.

Corrections and additions to sv_SE locale

---

classes/search/SubmissionSearch.inc.php

see https://github.com/pkp/pkp-lib/issues/2575#issuecomment-343289804

separating hookResult and queryResults

---

classes/context/Context.inc.php
classes/controllers/grid/GridHandler.inc.php
classes/core/PKPApplication.inc.php
classes/plugins/ReportPlugin.inc.php
classes/session/SessionManager.inc.php
classes/statistics/PKPMetricsDAO.inc.php
lib/adodb/adodb-datadict.inc.php
lib/adodb/datadict/datadict-mysql.inc.php
lib/adodb/datadict/datadict-postgres.inc.php
lib/adodb/drivers/adodb-mysql.inc.php
locale/ar_IQ/manager.xml
locale/de_DE/manager.xml
locale/en_US/manager.xml
locale/fi_FI/manager.xml
locale/ru_RU/manager.xml
locale/sv_SE/manager.xml

Switch URL for pkp.sfu.ca from HTTP to HTTPS

---

controllers/grid/users/reviewer/form/ReviewerForm.inc.php
controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php

s. https://github.com/pkp/pkp-lib/issues/3046

pkp/pkp-lib#3046 getCustomTemplateKeys parameters

---

controllers/api/file/PKPManageFileApiHandler.inc.php

File deletion from revision grid is broken 

---

js/controllers/SiteHandler.js

fix JS linting error

---

controllers/api/file/PKPManageFileApiHandler.inc.php
controllers/grid/files/review/AuthorReviewRevisionsGridHandler.inc.php

Allow authors to delete from revisions grid

---

controllers/grid/files/review/AuthorReviewRevisionsGridHandler.inc.php

Allow authors to delete from revisions grid #3063

---

classes/citation/Citation.inc.php
classes/citation/CitationDAO.inc.php
controllers/modals/submissionMetadata/PublicationEntryHandler.inc.php
controllers/tab/publicationEntry/PublicationEntryTabHandler.inc.php
controllers/tab/publicationEntry/form/CitationsForm.inc.php
locale/en_US/submission.xml
templates/controllers/tab/publicationEntry/form/citationsForm.tpl
templates/submission/submissionMetadataFormFields.tpl
tools/parseCitations.php
xml/schema/metadata.xml

s. https://github.com/pkp/pkp-lib/issues/3028

 pkp/pkp-lib#3028 parse and save citations 

---

locale/pt_BR/admin.xml
locale/pt_BR/api.xml
locale/pt_BR/submission.xml

pt_BR update

---

locale/de_DE/common.xml
locale/de_DE/manager.xml

* Add new parameter to text and update translation.
* Remove text which is no longer used.
* Add missing text.

Update German translations

---

classes/file/SubmissionFileManager.inc.php

Hi @asmecher, here's that PR ...

pkp/pkp-lib#3122 Add copyFile method to SubmissionFileManager

---

locale/de_DE/submission.xml
locale/ru_RU/submission.xml

locale updates

---

pages/workflow/PKPWorkflowHandler.inc.php
templates/workflow/editorialLinkActions.tpl

s. https://github.com/pkp/pkp-lib/issues/3039

pkp/pkp-lib#3039 editor actions for all managers and sub-editors

---

locale/en_US/submission.xml

submission.event.participantAdded  was repeated in two lines 277 and 288

delete repeated key English submission.xml

---

locale/ar_IQ/submission.xml
locale/cs_CZ/submission.xml
locale/da_DK/submission.xml
locale/de_DE/submission.xml
locale/fi_FI/submission.xml
locale/fr_CA/submission.xml
locale/fr_FR/submission.xml
locale/pl_PL/submission.xml
locale/pt_BR/submission.xml
locale/sr_RS@cyrillic/submission.xml
locale/sr_RS@latin/submission.xml
locale/sv_SE/submission.xml

locale updates, removed duplicate key

---

styles/controllers/notification.less

Fix positioning and style of notifications placed above main content

---

classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php

add reviewer recommendation to imported comments #2628

---

classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php

add reviewer recommendation to imported comments 

---

classes/submission/Submission.inc.php

I found a small typo in Submission.inc.php.

fixed typo in Submission.inc.php

---

plugins/generic/usageStats/PKPUsageStatsLoader.inc.php
plugins/generic/usageStats/tests/PKPUsageStatsLoaderTest.php

Add submodule and test to ensure file is present and readable.  Resolves pkp/pkp-lib#3204.
Adding the test involves refactoring the formerly private method.

Fix submodule for COUNTER bots.

---

locale/cs_CZ/common.xml
locale/de_DE/common.xml
locale/el_GR/common.xml
locale/en_US/common.xml
locale/es_AR/common.xml
locale/es_ES/common.xml
locale/eu_ES/common.xml
locale/fa_IR/common.xml
locale/fr_CA/common.xml
locale/it_IT/common.xml
locale/ja_JP/common.xml
locale/nl_NL/common.xml
locale/pt_BR/common.xml
locale/pt_PT/common.xml
locale/ru_RU/common.xml
locale/tr_TR/common.xml
locale/uk_UA/common.xml

Resolves pkp/pkp-lib#3235, with new licensebuttons.net URL.

pkp/pkp-lib#3235: Update CC license images to protocol relative URLs

---

classes/plugins/BlockPlugin.inc.php
classes/plugins/Plugin.inc.php
classes/plugins/ThemePlugin.inc.php
classes/template/PKPTemplateResource.inc.php
plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php
plugins/generic/usageStats/UsageStatsHandler.inc.php
plugins/generic/usageStats/UsageStatsSettingsForm.inc.php

- Adds template resource for each enabled plugin.
- Use template resources in block plugins.
- Allow themes to override templates from plugin template resources.

pkp/pkp-lib#2872 Allow themes to override templates in block plugins.

---

locale/es_ES/editor.xml

I just correct the wrong word ususario to usuario

ususario to usuario (wrong word)

---

locale/fa_IR/bic21subjects.xml

fixed the extra quotation mark problem mentioned by @bozana 
https://github.com/pkp/pkp-lib/pull/3308#issuecomment-361757510

fixed mistake " problem

---

plugins/importexport/native/filter/NativeXmlSubmissionFilter.inc.php

s. https://github.com/pkp/pkp-lib/issues/3348

pkp/pkp-lib#3348 fix article pubId native import

---

plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php
plugins/importexport/native/pkp-native.xsd

s. https://github.com/pkp/pkp-lib/issues/3357

pkp/pkp-lib#3357 fix discipline typo in native import/export

---

pages/workflow/PKPWorkflowHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/3359

pkp/pkp-lib#3359 recommendOnly editor and section editor fix

---

classes/mail/EmailTemplateDAO.inc.php

s. https://github.com/pkp/pkp-lib/issues/3390

pkp/pkp-lib#3390 fix email templates install/upgrade

---

locale/de_DE/common.xml
locale/de_DE/user.xml

Update German translation (issue #2972)

---

controllers/grid/users/stageParticipant/StageParticipantGridHandler.inc.php
controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php

s. https://github.com/pkp/pkp-lib/issues/3398

pkp/pkp-lib#3398 fix duplicate pre-review discussion entries

---

classes/navigationMenu/NavigationMenuItemDAO.inc.php
locale/en_US/manager.xml
pages/sitemap/PKPSitemapHandler.inc.php
templates/controllers/tab/settings/contextIndexing/form/contextIndexingForm.tpl

s. https://github.com/pkp/pkp-lib/issues/3459

pkp/pkp-lib#3459 get menu items by type and contextId

---

js/controllers/grid/users/stageParticipant/form/StageParticipantNotifyHandler.js

s. https://github.com/pkp/pkp-lib/issues/3444

pkp/pkp-lib#3444 check if there are e-mail variables

---

controllers/modals/editorDecision/form/RecommendationForm.inc.php

s. https://github.com/pkp/pkp-lib/issues/3481

pkp/pkp-lib#3481 fix submission URL in recommendation emails

---

locale/uk_UA/admin.xml
locale/uk_UA/common.xml
locale/uk_UA/countries.xml
locale/uk_UA/currencies.xml
locale/uk_UA/default.xml
locale/uk_UA/editor.xml
locale/uk_UA/grid.xml
locale/uk_UA/installer.xml
locale/uk_UA/languages.xml
locale/uk_UA/manager.xml
locale/uk_UA/reader.xml
locale/uk_UA/reviewer.xml
locale/uk_UA/submission.xml
locale/uk_UA/user.xml

Ukrainian locale.
Most of the work on this translation was done by Oleh Sukhovirskyi, Khmelnytskyi Humanitarian-Pedagogical Academy (Khmelnytskyi, Ukraine).
Also, some files were translated by Danylo Pysanets, Bogomolets National Medical University (Kyiv, Ukraine).

Ukrainian translation

---

locale/sv_SE/api.xml
locale/sv_SE/common.xml
locale/sv_SE/editor.xml
locale/sv_SE/grid.xml
locale/sv_SE/installer.xml
locale/sv_SE/manager.xml
locale/sv_SE/submission.xml
locale/sv_SE/user.xml

Please find updated Swedish locale files. Plugin updates not yet completed.

Updating sv_SE locale for 3.1.1

---

locale/fi_FI/editor.xml
locale/fi_FI/submission.xml

@asmecher 
These are the changes from Nates last pr for fi locale.

Last fi locale additions to 3.1.1

---

locale/sv_SE/editor.xml
locale/sv_SE/submission.xml

Hi @asmecher, here are the last changes also for the sv_SE locale. Still some remaining plugin translations which I will attend to, but those will have to be separate from the release, and maybe be cherry-picked to 3.1.1.

Final update for sv_SE and 3.1.1

---

classes/plugins/Plugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/3556

pkp/pkp-lib#3556 fix basePath in getTemplatePath()

---

plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php
plugins/generic/usageStats/UsageStatsOptoutBlockPlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/3580

pkp/pkp-lib#3580 fix UsageStatsOptoutBlockPlugin display

---

controllers/grid/files/submission/SubmissionWizardFilesGridHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/3640

pkp/pkp-lib#3640 no viewInformationCenter link for authors

---

classes/notification/form/PKPNotificationSettingsForm.inc.php

pkp/pkp-lib#3637: check for null context in notification form

---

controllers/grid/users/reviewer/form/EditReviewForm.inc.php
controllers/grid/users/reviewer/form/ReviewerForm.inc.php
templates/controllers/grid/users/reviewer/form/editReviewForm.tpl
templates/controllers/grid/users/reviewer/form/reviewerFormFooter.tpl

@NateWr 
see https://github.com/pkp/pkp-lib/issues/3608
- Change the label for the default form to "None / Free Form Review" in reviewForm and editReviewForm
- Allow managers to change the review form as long as the review is not completed

pkp/pkp-lib#3608 Allow managers change review form if review not completed

---

locale/da_DK/common.xml
locale/da_DK/editor.xml
locale/da_DK/grid.xml
locale/da_DK/installer.xml
locale/da_DK/manager.xml
locale/da_DK/reviewer.xml
locale/da_DK/submission.xml
locale/da_DK/user.xml

Updates to the danish translation from @neffe
Note that duplicate and obsolete keys have been trimmed away as well.

Translation update for the da_DK locale

---

classes/reviewForm/ReviewFormDAO.inc.php
classes/services/UserService.inc.php
classes/services/queryBuilders/UserListQueryBuilder.inc.php
classes/user/PKPUserDAO.inc.php
controllers/list/users/SelectReviewerListHandler.inc.php
locale/en_US/editor.xml

This commit also adds a count of declined reviews to the API response.

pkp/pkp-ilb#3590 Don't include declined reviews in active count.

---

locale/de_DE/common.xml
locale/de_DE/grid.xml
locale/de_DE/installer.xml
locale/de_DE/manager.xml
locale/de_DE/submission.xml

updated the de_DE locale according to the latest changes to the en_US locale

de_DE locate updates

---

locale/de_DE/common.xml
locale/de_DE/countries.xml
locale/de_DE/editor.xml
locale/de_DE/languages.xml
locale/de_DE/submission.xml
locale/de_DE/user.xml
plugins/generic/acron/locale/de_DE/locale.xml

Added some missing lines, mostly around new review features

de_DE locale update, aligning with en_US locale

---

classes/file/SubmissionFileManager.inc.php

s. https://github.com/pkp/pkp-lib/issues/3741

pkp/pkp-lib#3741 do not copy file in the files folder before DB insert

---

locale/sv_SE/common.xml
locale/sv_SE/manager.xml
locale/sv_SE/submission.xml
locale/sv_SE/user.xml

PR in ojs will follow. Cherry-pick to OJS 3.1.1-1 is appreciated.

Updating sv_SE locale for 3.1.1-1

---

locale/de_DE/manager.xml
locale/de_DE/submission.xml
locale/de_DE/user.xml
locale/en_US/user.xml

* de_DE locale updates, aligning de_DE with en_US
* including a minor update to recently introduces en_US locale string, @NateWr, could you have a quick look?

Locale updates en_US, de_DE - privacy policy language

---

classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php
controllers/grid/queries/form/QueryForm.inc.php
locale/da_DK/common.xml
locale/de_DE/common.xml

s. https://github.com/pkp/pkp-lib/issues/3792

pkp/pkp-lib#3792 Update list separator locale key

---

classes/webservice/WebService.inc.php

s. https://github.com/pkp/pkp-lib/issues/3779

pkp/pkp-lib#3779 possibility to set ssl version in WebService class

---

classes/security/UserGroupDAO.inc.php

s. https://github.com/pkp/pkp-lib/issues/3802

pkp/pkp-lib#3802 use select distinct in UserGropDAO::getUsersNotInRole

---

classes/stageAssignment/StageAssignmentDAO.inc.php

s. https://github.com/pkp/pkp-lib/issues/3811

pkp/pkp-lib#3811 fix StageAssignmentDAO::updateObject

---

locale/es_ES/common.xml

Reported here:
https://forum.pkp.sfu.ca/t/assign-evaluation-characters-appear-ojs-3-x/45721
@mtub this merge is important. Otherwise ojs will be defaced in Spanish.

Missing important chain (separator)

---

classes/admin/form/PKPSiteSettingsForm.inc.php
classes/user/form/LoginChangePasswordForm.inc.php
controllers/grid/settings/user/UserGridHandler.inc.php
controllers/grid/settings/user/form/UserDetailsForm.inc.php
controllers/grid/settings/user/form/UserDisableForm.inc.php
controllers/grid/settings/user/form/UserForm.inc.php
controllers/grid/settings/user/form/UserRoleForm.inc.php
controllers/grid/users/author/AuthorGridHandler.inc.php

Fixes part of #3578; may break some plugins.

pkp/pkp-lib#3578: harmonizing Form::display() signatures

---

controllers/grid/users/reviewer/form/EditReviewForm.inc.php

s. https://github.com/pkp/pkp-lib/issues/3810

pkp/pkp-lib#3810 fix review assignemnt function calls in EditReviewForm

---

tools/installPluginVersion.php

s. https://github.com/pkp/pkp-lib/issues/3868

pkp/pkp-lib#3868 fix installPluginVersion tool

---

controllers/grid/admin/systemInfo/SystemInfoGridCategoryRow.inc.php
controllers/grid/files/LibraryFileGridCategoryRow.inc.php
controllers/grid/files/SubmissionFilesGridRow.inc.php

pkp/pkp-lib#3578: harmonizing GridRow::initialize() signatures

---

classes/file/FileManager.inc.php
classes/file/PKPLibraryFileManager.inc.php
classes/file/PKPPublicFileManager.inc.php
classes/file/SubmissionFileManager.inc.php
classes/file/TemporaryFileManager.inc.php
classes/plugins/PluginHelper.inc.php
classes/scheduledTask/ScheduledTaskHelper.inc.php
classes/submission/SubmissionFileDAODelegate.inc.php
controllers/api/file/FileApiHandler.inc.php
controllers/api/file/PKPManageFileApiHandler.inc.php
controllers/grid/files/LibraryFileGridHandler.inc.php
controllers/grid/files/submissionDocuments/form/NewLibraryFileForm.inc.php
controllers/grid/settings/library/form/NewLibraryFileForm.inc.php
controllers/tab/settings/form/SettingsFileUploadForm.inc.php
pages/libraryFiles/LibraryFileHandler.inc.php
plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php
plugins/importexport/users/PKPUserImportExportPlugin.inc.php
tools/copyAccessLogFileTool.php

Addresses part of  #3578 as discussed on Slack. Will break some plugins.

pkp/pkp-lib#3578: cleaning up FileManager signatures

---

locale/fi_FI/common.xml
locale/fi_FI/editor.xml
locale/fi_FI/manager.xml
locale/fi_FI/submission.xml
locale/fi_FI/user.xml

Finnish translation for 3.1.1-2

---

classes/controllers/modals/submissionMetadata/SubmissionMetadataHandler.inc.php
classes/controllers/tab/settings/SettingsTabHandler.inc.php
classes/controllers/tab/settings/form/ContextSettingsForm.inc.php
controllers/grid/admin/languages/AdminLanguageGridHandler.inc.php
controllers/grid/languages/form/InstallLanguageForm.inc.php
controllers/grid/users/stageParticipant/StageParticipantGridHandler.inc.php
controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php
controllers/tab/settings/paymentMethod/form/PaymentMethodForm.inc.php

Fixes part of #3578; may break some plugins.

pkp/pkp-lib#3578: harmonizing Form::readInputData() signatures

---

classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php
controllers/grid/admin/languages/AdminLanguageGridHandler.inc.php
controllers/grid/navigationMenus/form/NavigationMenuForm.inc.php
controllers/grid/navigationMenus/form/NavigationMenuItemsForm.inc.php
controllers/grid/users/stageParticipant/form/AddParticipantForm.inc.php
controllers/tab/pubIds/form/PKPPublicIdentifiersForm.inc.php
controllers/tab/publicationEntry/PublicationEntryTabHandler.inc.php
controllers/tab/settings/paymentMethod/form/PaymentMethodForm.inc.php
controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php
controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php

Fixes part of #3578; may break some plugins.

pkp/pkp-lib#3578: harmonizing Form::validate() signatures

---

controllers/grid/users/reviewer/form/EditReviewForm.inc.php

@asmecher this pr just removes the author notification part, which will potentially cause confusion. 
https://github.com/pkp/pkp-lib/issues/3983

Remove author notification for changed review assignments

---

controllers/grid/files/review/ReviewCategoryGridDataProvider.inc.php
controllers/grid/files/submissionDocuments/SubmissionDocumentsFilesGridDataProvider.inc.php
controllers/grid/settings/library/LibraryFileAdminGridDataProvider.inc.php

pkp/pkp-lib#3578: harmonizing GridDataProvider::loadCategoryData() signatures

---

locale/fi_FI/submission.xml

After seeing these in context...

Fix correct translation for responseDue and reviewDue

---

locale/ar_IQ/reader.xml
locale/cs_CZ/reader.xml
locale/da_DK/reader.xml
locale/de_DE/reader.xml
locale/el_GR/reader.xml
locale/en_US/reader.xml
locale/es_ES/reader.xml
locale/eu_ES/reader.xml
locale/fa_IR/reader.xml
locale/fi_FI/reader.xml
locale/fr_CA/reader.xml
locale/fr_FR/reader.xml
locale/id_ID/reader.xml
locale/it_IT/reader.xml
locale/nb_NO/reader.xml
locale/nl_NL/reader.xml
locale/pl_PL/reader.xml
locale/pt_BR/reader.xml
locale/pt_PT/reader.xml
locale/ru_RU/reader.xml
locale/sl_SI/reader.xml
locale/sr_RS@cyrillic/reader.xml
locale/sr_RS@latin/reader.xml
locale/sv_SE/reader.xml
locale/tr_TR/reader.xml
locale/uk_UA/reader.xml
locale/zh_CN/reader.xml

as reported in #4002 by @kant 
@asmecher, could you have a quick look?

Update addthis support URLs

---

controllers/grid/settings/roles/UserGroupGridHandler.inc.php
controllers/informationCenter/FileInformationCenterHandler.inc.php
controllers/informationCenter/InformationCenterHandler.inc.php
controllers/modals/documentLibrary/DocumentLibraryHandler.inc.php
controllers/modals/submissionMetadata/PublicationEntryHandler.inc.php
controllers/tab/settings/AdminSettingsTabHandler.inc.php
controllers/tab/settings/ManagerSettingsTabHandler.inc.php
controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php
pages/admin/AdminHandler.inc.php
pages/management/ManagementHandler.inc.php
pages/user/RegistrationHandler.inc.php
pages/workflow/PKPWorkflowHandler.inc.php

pkp/pkp-lib#3578: harmonizing PKPHandler::initialize() signatures

---

classes/submission/reviewer/form/ReviewerReviewStep1Form.inc.php

pkp/pkp-lib#4026 Review process step 1, fixed missing privacy consent error message translation

---

plugins/generic/usageStats/locale/es_ES/locale.xml

The text in Spanish was wrong. Here goes a better version ;-)

Improve text when no download info is available

---

locale/es_ES/manager.xml

this PR is according to issue #4067

update manager.xml Spanish translation

---

locale/ar_IQ/common.xml
locale/ar_IQ/editor.xml
locale/ar_IQ/grid.xml
locale/ar_IQ/installer.xml
locale/ar_IQ/manager.xml
locale/ar_IQ/submission.xml
locale/ar_IQ/user.xml

Arabic locale files have to be updated after the release of OJS 3.1.1-4

Updating Arabic language files before the end of September

---

locale/es_ES/submission.xml

@mtub  this is for replacing #3627 because I change my nick from t4x0n to carzamora. 
I think this is the problem for sign my old PR.

update es_ES translation in context (new)

---

classes/mail/SMTPMailer.inc.php

pkp/pkp-lib#4137: log SMTP connect failure

---

locale/pt_PT/common.xml
locale/pt_PT/editor.xml
locale/pt_PT/manager.xml
locale/pt_PT/submission.xml
locale/pt_PT/user.xml

cherry-picked from #4152, translation by @ambs 
#4190

Add pt_PT translations

---

classes/mail/SMTPMailer.inc.php

Resolves bug in fix for pkp/pkp-lib#4137

pkp/pkp-lib#4137: Fix test of SMTP connection error reporting

---

classes/log/PKPSubmissionEmailLogEntry.inc.php
controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php

See https://github.com/pkp/pkp-lib/issues/4070

Add sender_id and event_type to logged REVISED_VERSION_NOTIFY messages

---

pages/management/PKPToolsHandler.inc.php

[pkp-lib/#4219](https://github.com/pkp/pkp-lib/issues/4219)

Add BOM (byte order mark) to fix UTF-8 in Excel

---

classes/template/PKPTemplateManager.inc.php

This explains my confusion... :joy:

pkp/pkp-lib#3404 Update jQuery version when CDN is enabled

---

styles/rtl.less

[pkp-lib/#4182](https://github.com/pkp/pkp-lib/issues/4182)

pkp/pkp-lib#4182 Fix modal disappearing in RTL languages

---

locale/ar_IQ/common.xml
locale/ca_ES/common.xml
locale/cs_CZ/common.xml
locale/da_DK/common.xml
locale/de_DE/common.xml
locale/en_US/common.xml
locale/es_ES/common.xml
locale/fa_IR/common.xml
locale/fi_FI/common.xml
locale/fr_CA/common.xml
locale/fr_FR/common.xml
locale/it_IT/common.xml
locale/pl_PL/common.xml
locale/pt_BR/common.xml
locale/pt_PT/common.xml
locale/ru_RU/common.xml
locale/sl_SI/common.xml
locale/sr_RS@cyrillic/common.xml
locale/sr_RS@latin/common.xml
locale/sv_SE/common.xml
locale/tr_TR/common.xml
locale/uk_UA/common.xml
templates/submission/submissionMetadataFormTitleFields.tpl

[pkp-lib/#3874](https://github.com/pkp/pkp-lib/issues/3874)

pkp/pkp-lib#3874 Clean up overspecific/wrong subtitle language

---

classes/plugins/PluginHelper.inc.php
controllers/grid/plugins/form/UploadPluginForm.inc.php

pkp/pkp-lib#4243: clarify errors when uploading a plugin archive fails

---

classes/db/DBConnection.inc.php
classes/services/queryBuilders/BaseQueryBuilder.inc.php

s. https://github.com/pkp/pkp-lib/issues/3860

 #3860 consider configured socket and port

---

templates/form/formSection.tpl
templates/submission/submissionMetadataFormFields.tpl

pkp/pkp-lib#4268 Fixed missing asterisk for required submission metadata fields

---

classes/context/PKPSection.inc.php
classes/context/PKPSectionDAO.inc.php
js/pages/submission/SubmissionStep1FormHandler.js
js/pages/submission/SubmissionStep2FormHandler.js
pages/about/AboutContextHandler.inc.php
pages/submission/PKPSubmissionHandler.inc.php
templates/frontend/pages/submissions.tpl
templates/submission/form/index.tpl
templates/submission/form/step1.tpl

Section policies display

---

js/controllers/NotificationHandler.js

pkp/pkp-lib#4330 NotificationHandler, fixed unbindPartial exception

---

classes/controllers/grid/GridHandler.inc.php

pkp/pkp-lib#4328 GridHandler now provides a "initFeatures" hook

---

js/controllers/form/FormHandler.js

pkp/pkp-lib#4320 error messages for check-boxes are now displayed below the label

---

classes/context/Category.inc.php
classes/context/CategoryDAO.inc.php
classes/core/PKPApplication.inc.php
classes/services/PKPSubmissionService.inc.php
classes/services/queryBuilders/PKPSubmissionListQueryBuilder.inc.php
classes/submission/PKPSubmissionMetadataFormImplementation.inc.php
classes/submission/SubmissionDAO.inc.php
controllers/grid/settings/category/CategoryCategoryGridHandler.inc.php
controllers/grid/settings/category/CategoryGridCategoryRow.inc.php
controllers/grid/settings/category/CategoryGridRow.inc.php
controllers/grid/settings/category/form/CategoryForm.inc.php
controllers/list/SelectCategoryListHandler.inc.php
controllers/modals/submissionMetadata/form/PKPSubmissionMetadataViewForm.inc.php
locale/ca_ES/submission.xml
locale/de_DE/submission.xml
locale/el_GR/submission.xml
locale/en_US/manager.xml
locale/en_US/submission.xml
locale/es_ES/manager.xml
locale/es_ES/submission.xml
locale/fr_CA/submission.xml
locale/pt_BR/submission.xml
locale/sl_SI/manager.xml
locale/sl_SI/submission.xml
pages/catalog/PKPCatalogHandler.inc.php
templates/controllers/grid/settings/category/form/categoryForm.tpl
templates/management/categories.tpl
templates/submission/form/categories.tpl
templates/submission/form/step3.tpl
xml/schema/categories.xml

Replaces https://github.com/pkp/pkp-lib/pull/4313

pkp/pkp-lib#4158 Add category support to OJS/pkp-lib

---

classes/citation/CitationDAO.inc.php
classes/plugins/PluginRegistry.inc.php
controllers/tab/publicationEntry/PublicationEntryTabHandler.inc.php
controllers/tab/publicationEntry/form/CitationsForm.inc.php
locale/en_US/submission.xml
templates/controllers/tab/publicationEntry/form/citationsForm.tpl

changes for crossref new deposit api and reference linking

Reference linking stable 3 1 2

---

classes/core/Core.inc.php

s. https://github.com/pkp/pkp-lib/issues/4390

pkp/pkp-lib#4390 fix counter bot caching in PHP 7.2

---

classes/core/Core.inc.php

s. https://github.com/pkp/pkp-lib/issues/4390

pkp/pkp-lib#4390 fix counter bot list caching in PHP 7.2

---

classes/form/validation/FormValidatorReCaptcha.inc.php
classes/user/form/RegistrationForm.inc.php

shared library component for pkp/pkp-lib#4204

pkp/pkp-lib#4204: enabled hostname enforcement for ReCAPTCHA

---

locale/en_US/user.xml

pkp/pkp-lib#4293 Distinguish the user's URL field from the ORCID field

---

classes/core/Core.inc.php

s. https://github.com/pkp/pkp-lib/issues/4403

pkp/pkp-lib#4403 consider case-insensitive bot match

---

templates/common/header.tpl
templates/controllers/notification/inPlaceNotification.tpl
templates/controllers/statistics/form/reportGeneratorForm.tpl
templates/form/formButtons.tpl
templates/submission/form/step1.tpl
templates/submission/form/step3.tpl

Pkp-lib#3831 Can't override core templates

---

locale/fi_FI/common.xml
locale/fi_FI/default.xml
locale/fi_FI/editor.xml
locale/fi_FI/grid.xml
locale/fi_FI/languages.xml
locale/fi_FI/manager.xml
locale/fi_FI/submission.xml
locale/fi_FI/user.xml

Fi locale for stable-3_1_2

---

locale/fi_FI/common.xml
locale/fi_FI/default.xml
locale/fi_FI/editor.xml
locale/fi_FI/grid.xml
locale/fi_FI/languages.xml
locale/fi_FI/manager.xml
locale/fi_FI/submission.xml
locale/fi_FI/user.xml

cherry-picked from stable-3_1_2

fi_FI locale update

---

.gitmodules
classes/core/Core.inc.php

s. https://github.com/pkp/pkp-lib/issues/4455

pkp/pkp-lib#4455 introduce counterBots submodule

---

classes/context/ContextDAO.inc.php
classes/security/RoleDAO.inc.php
classes/services/PKPNavigationMenuService.inc.php
classes/services/PKPSubmissionService.inc.php
controllers/grid/queries/form/QueryForm.inc.php
pages/dashboard/DashboardHandler.inc.php
pages/user/ProfileHandler.inc.php

s. https://github.com/pkp/pkp-lib/issues/4340

pkp/pkp-lib#4340 Users in multicontext install are offered links to unprivileged contexts

---

controllers/grid/queries/QueriesGridCellProvider.inc.php
controllers/grid/queries/QueryNotesGridCellProvider.inc.php

Hi
minimal solution for my issue
it's a proposition...

pkp/pkp-lib#4452 change date format for Notes in Queries

---

locale/en_US/common.xml

add date decided locale key

---

locale/ar_IQ/submission.xml
locale/ca_ES/submission.xml
locale/cs_CZ/submission.xml
locale/da_DK/submission.xml
locale/de_DE/submission.xml
locale/el_GR/submission.xml
locale/en_US/submission.xml
locale/es_ES/submission.xml
locale/eu_ES/submission.xml
locale/fa_IR/submission.xml
locale/fi_FI/submission.xml
locale/fr_CA/submission.xml
locale/fr_FR/submission.xml
locale/hr_HR/submission.xml
locale/id_ID/submission.xml
locale/it_IT/submission.xml
locale/nb_NO/submission.xml
locale/nl_NL/submission.xml
locale/pl_PL/submission.xml
locale/pt_BR/submission.xml
locale/pt_PT/submission.xml
locale/ru_RU/submission.xml
locale/sl_SI/submission.xml
locale/sr_RS@cyrillic/submission.xml
locale/sr_RS@latin/submission.xml
locale/sv_SE/submission.xml
locale/tr_TR/submission.xml
locale/uk_UA/submission.xml
locale/zh_CN/submission.xml

pkp/pkp-lib#3535 Updating the Section settings heading

---

locale/ru_RU/common.xml

cherry-picked from `master` branch @ppv1979

ru_RU locale update

---

classes/install/Installer.inc.php

#3594 broke upgrade on postgres

make upgrade work again on postgres

---

api/v1/stats/PKPStatsHandler.inc.php
classes/core/APIRouter.inc.php
classes/services/PKPStatsService.inc.php
classes/services/PKPSubmissionService.inc.php
classes/services/queryBuilders/PKPStatsListQueryBuilder.inc.php
classes/statistics/PKPMetricsDAO.inc.php
classes/statistics/PKPStatisticsHelper.inc.php
controllers/stats/StatsComponentHandler.inc.php
locale/en_US/api.xml
locale/en_US/common.xml
locale/en_US/manager.xml
pages/stats/PKPStatsHandler.inc.php
styles/structure/body.less
templates/common/header.tpl
templates/management/tools/index.tpl
templates/stats/articles.tpl
templates/stats/publishedSubmissions.tpl

s. https://github.com/pkp/pkp-lib/issues/3673

pkp/pkp-lib#3673 Common work for data visualization

---

classes/submission/PKPAuthorDAO.inc.php
classes/submission/PKPSubmissionMetadataFormImplementation.inc.php
classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php
classes/user/UserDAO.inc.php
controllers/grid/admin/languages/AdminLanguageGridHandler.inc.php
controllers/grid/languages/LanguageGridCellProvider.inc.php
locale/en_US/admin.xml

s. https://github.com/pkp/pkp-lib/issues/3784

user and author names update when site primary locale and submission locale change

---

classes/citation/CitationDAO.inc.php
classes/plugins/PluginRegistry.inc.php
controllers/tab/publicationEntry/PublicationEntryTabHandler.inc.php
controllers/tab/publicationEntry/form/CitationsForm.inc.php
locale/en_US/submission.xml
templates/controllers/tab/publicationEntry/form/citationsForm.tpl

s. https://github.com/pkp/pkp-lib/issues/3803

changes for reference linking

---

controllers/tab/pubIds/form/PKPPublicIdentifiersForm.inc.php

pkp/pkp-lib#4542: Disallow slash from public url identifier (master)

---

classes/admin/form/PKPSiteSettingsForm.inc.php

https://github.com/pkp/pkp-lib/issues/4571

pkp/pkp-lib#4571 use getDefaultFormLocale

---

controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php

Provide authorName assignment.

pkp/pkp-lib#4613 assign authorName parameter

---

controllers/grid/queries/QueriesGridHandler.inc.php
controllers/grid/queries/form/QueryNoteForm.inc.php
js/controllers/grid/queries/ReadQueryHandler.js
locale/en_US/submission.xml
styles/controllers/grid/queries.less
templates/controllers/grid/queries/readQuery.tpl

https://github.com/pkp/pkp-lib/issues/4556

pkp/pkp-lib#4556 Always include current user to query participants

---

locale/pt_BR/editor.xml

The entire <-- Reviewer selection lists --> block was missing on the pt_BR locale.

Update pt_BR locale on Reviewer Selection List

---

classes/plugins/ThemePlugin.inc.php
classes/template/PKPTemplateManager.inc.php

@NateWr fixed a bug before I could add the theme option.

#3817 Addendum to the original issue

---

classes/user/form/RegistrationForm.inc.php

Resolves pkp/pkp-lib#4649 for 3.1.2.  Needs a cherry-pick to master.

pkp/pkp-lib#4649: Fix email validation at registration

---

classes/search/SubmissionSearch.inc.php
classes/services/queryBuilders/PKPSubmissionQueryBuilder.inc.php
controllers/statistics/ReportGeneratorHandler.inc.php
controllers/tab/workflow/PKPWorkflowTabHandler.inc.php

Rename publishedArticle to publishedSubmission

---

locale/de_DE/submission.xml
locale/en_US/submission.xml

Hi @asmecher ,
these translation keys support the PR
https://github.com/pkp/omp/pull/682

[Translation] language keys to support chapter abstracts

---

api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php
api/v1/stats/publications/PKPStatsPublicationHandler.inc.php
classes/components/listPanels/PKPSubmissionsListPanel.inc.php
classes/filter/ClassTypeDescription.inc.php
classes/services/queryBuilders/PKPSubmissionQueryBuilder.inc.php
classes/submission/PKPSubmission.inc.php
classes/submission/PKPSubmissionDAO.inc.php
controllers/statistics/ReportGeneratorHandler.inc.php
pages/catalog/PKPCatalogHandler.inc.php
plugins/metadata/mods34/tests/filter/Mods34SchemaSubmissionAdapterTest.php
tests/data/PKPStatsTest.inc.php

Rename Submission to PKPSubmission & SubmissionDAO to PKPSubmissionDAO

Rename submission and submissiondao classes

---

locale/de_DE/submission.xml
locale/es_ES/submission.xml
locale/fi_FI/submission.xml
locale/nl_NL/submission.xml
locale/pt_BR/submission.xml
locale/sl_SI/submission.xml

Key was renamed in pkp/pkp-lib#4446.

pkp/pkp-lib#4901 Missing translation key

---

classes/services/PKPSubmissionService.inc.php

Resolves pkp/pkp-lib#4231 for the time being.

pkp/pkp-lib#4231: Ensure submissions without an active review round set a files count

---

locale/pt_BR/user.xml

Added missing PT_BR translations.

Update user.xml pt_BR

---

locale/es_ES/manager.xml

Translations based on manager.xml file that comes with OJS 3.1.2.1 . There seem to be some texts removed from master branch, not sure if that's correct

Complete manager.xml es_ES translations

---

locale/es_ES/submission.xml

I think this locale is now fully translated into es_ES

Complete submission.xml

---

LICENSE

https://github.com/pkp/pkp-lib/issues/5051

Adding the GPLv2 LICENSE file

---

js/controllers/SiteHandler.js
js/pages/header/TasksHandler.js

Added an option to clear the "callWhenClickOutside" callbacks and fixed the tasks popover.
Should I open a PR against OJS to update the /js/pkp.min.js?

pkp/pkp-lib#4984 Fixes the tasks popover

---

locale/pt_BR/user.xml

Corrected typo in "user.login.registerNewAccount".

Correction of typo in user.xml

---

classes/services/queryBuilders/PKPPublicationQueryBuilder.inc.php

@NateWr This does not fix the search in master branch yet, because the code is not migrated to support the new db design. Therefore I am skipping the tests with this one since there is a lot more work to be done here.

Fix query escaping in getDateBoundaries

---

classes/db/SchemaDAO.inc.php
classes/publication/PKPPublicationDAO.inc.php
classes/services/PKPPublicationService.inc.php
locale/en_US/submission.xml
schemas/publication.json

- Change date_published column from datetime to date
- Remove unused publicationType and publicationDateType properties

pkp/pkp-lib#5044 Modify datePublished support

---

classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php

Automatically add section editors to the initial submission discussion (comments for the editor).

pkp/pkp-lib#3910 Allow section editors to access the comments for the editor

---

classes/form/Form.inc.php
controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php

pkp/pkp-lib#5146: Enable execute hook for SubmissionsFilesUploadForm

---

classes/plugins/GatewayPlugin.inc.php

Change required to support:
See: https://github.com/pkp/ojs/pull/2360

add addPolicies method to the GatewayPlugin abstract class

---

classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php

https://github.com/pkp/pkp-lib/issues/3343

Show user's email when searching for existing users

---

locale/fr_CA/common.xml
locale/fr_CA/manager.xml

A few fixes (same fixes that have been also changed to the corresponding `*.po` files in the `master `branch)

fr_CA translation updated

---

locale/fr_CA/editor.xml

"Demande" is more suited than "Requête" here...
Sorry I had forgotten to commit those changes previously for proper adequation with the *.po files : https://github.com/pkp/pkp-lib/blob/49a91d565b2e60da4d3ba1044e102d9c8bfb0f04/locale/fr_CA/editor.po#L200

quick fixes

---

templates/frontend/components/header.tpl

Replaces https://github.com/pkp/pkp-lib/pull/4922.
cc @thinkbulecount2

pkp/pkp-lib#4684 Add mobile nav menu to default theme

---

templates/dashboard/index.tpl

From this issue: https://github.com/pkp/pkp-lib/issues/2617

pkp/pkp-lib#2617 Added badge count to My Queue in submissions

---

api/v1/site/PKPSiteHandler.inc.php
classes/components/forms/site/PKPSiteAppearanceForm.inc.php
classes/components/forms/site/PKPSiteConfigForm.inc.php
classes/components/forms/site/PKPSiteInformationForm.inc.php
classes/core/PKPApplication.inc.php
controllers/grid/admin/context/ContextGridHandler.inc.php
pages/admin/AdminHandler.inc.php
schemas/site.json
templates/admin/contexts.tpl
templates/admin/index.tpl
templates/admin/settings.tpl

(All the file additions here are just migrating stuff out of OJS and into pkp-lib.)

pkp/pkp-lib#4762 Restore multipress support for OMP

---

locale/fr_CA/common.xml

Updated fr_CA locale : Micro-fix

---

classes/form/validation/FormValidatorLength.inc.php

Resolves pkp/pkp-lib#5270 for master

pkp/pkp-lib#5270: Length validator references its own length

---

locale/fr_CA/common.po
locale/fr_CA/editor.po
locale/fr_CA/manager.po
locale/fr_CA/submission.po

Updated fr_CA locale

---

locale/pt_BR/submission.po

Added missing translations in discussions.

Added missing strings to submission.po pt_BR

---

locale/pt_BR/editor.po

Corrected string that said "reviews" instead of "revisions".

Correction to editor.po pt_BR

---

classes/components/forms/FieldPubId.inc.php

https://github.com/pkp/pkp-lib/issues/5254

Add publicationId as possible pubId component

---

classes/services/queryBuilders/SubmissionStatisticsQueryBuilder.inc.php

That's how this `$dateFormat` piece was expected to work, which should change the value of published submissions =]
My overall opinion about the Illuminate\Database is that it works great for simple queries, but since it's missing too many constructions (I'm not sure it exists something better in PHP), we end up using too much "raw" and the bound parameters are lost in the process, which requires the use of [merge bindings](https://laravel.com/api/5.7/Illuminate/Database/Query/Builder.html#method_mergeBindings) (a shortcut for `array_merge_recursive` that end up producing unexpected results)/reorder the parameters manually... If only they had added named parameters, everything could be cleaner 🤔

pkp/pkp-lib#5319 Fixed missing date filter.

---

classes/notification/managerDelegate/EditorialReportNotificationManager.inc.php
classes/services/EditorialStatisticsService.inc.php
classes/task/StatisticsReport.inc.php

I saw the average by year was removed, but these pieces of code remained.
ps: I can update the `SubmissionStatisticsQueryBuilder.inc.php` if needed.

pkp/pkp-lib#5335 Fixed notices and loaded missing locale.

---

classes/core/Dispatcher.inc.php
classes/core/PKPServices.inc.php

pkp/pkp-lib#4383 added `PKPServices::beforeGet` hook to allow service registration from plugins

---

locale/da_DK/manager.po

Currently translated at 86.4% (557 of 645 strings)
Translation: PKP Web Application Library/manager
Translate-URL: http://translate.pkp.sfu.ca/projects/pkp-lib/manager/da/

Translated using Weblate (Danish)

---

classes/components/forms/FieldText.inc.php
classes/components/forms/publication/PKPPublicationLicenseForm.inc.php
classes/services/PKPPublicationService.inc.php
locale/en_US/common.po
locale/en_US/submission.po
pages/workflow/PKPWorkflowHandler.inc.php
schemas/publication.json

- Adds text describing the default that will be applied on publishing
- Applies defaults on publishing
- Requires editors to opt into editing copyright and license info

pkp/pkp-lib#5428 Improve UX of publication permissions settings

---

classes/services/queryBuilders/PKPSubmissionQueryBuilder.inc.php
controllers/grid/settings/category/CategoryCategoryGridHandler.inc.php
js/classes/features/OrderCategoryGridItemsFeature.js
schemas/publication.json
templates/controllers/grid/grid.tpl

- Restores seq property to publications
- Fixes ordering in all category grids

pkp/pkp-lib#5438 Fix ordering submissions in table of contents

---

classes/components/forms/FormComponent.inc.php
classes/components/forms/context/PKPLicenseForm.inc.php
classes/components/forms/context/PKPReviewGuidanceForm.inc.php
classes/components/forms/context/PKPReviewSetupForm.inc.php
styles/helpers.less

- Fixes places where button could not be clicked.
- Removes links embedded in form fields that did not open
to the right help text

pkp/pkp-lib#5441 Fix errors with in-app help links

---

classes/context/Context.inc.php
classes/db/SettingsDAO.inc.php
controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php

This reverts commit a7a341b605110a50369d2e6e55a41beeef902739.

pkp/pkp-lib#5550 Revert "Update SettingsDAO for removed settings_type column"

---

templates/frontend/components/registrationForm.tpl
templates/frontend/pages/userLogin.tpl
templates/frontend/pages/userLostPassword.tpl

From this issue: https://github.com/pkp/pkp-lib/issues/5186

i5186 Add aria-required to register and login forms

---

classes/form/validation/FormValidatorCustom.inc.php
classes/security/Validation.inc.php
controllers/grid/settings/user/form/UserDetailsForm.inc.php

Generate site minimum-length password

---

classes/db/DAO.inc.php

@asmecher Any objection to this?

Throw an exception when a database error occurs

---

locale/en_US/submission.po

For this issue: https://github.com/pkp/pkp-lib/issues/5190

i5190 Added localised strings for iframe title

---

classes/security/authorization/internal/QueryUserAccessibleWorkflowStageRequiredPolicy.inc.php

https://github.com/pkp/pkp-lib/issues/5661

Fix discussions grid for reviewers

---

classes/form/FormBuilderVocabulary.inc.php
classes/submission/reviewer/form/PKPReviewerReviewStep1Form.inc.php
classes/submission/reviewer/form/PKPReviewerReviewStep2Form.inc.php
classes/submission/reviewer/form/PKPReviewerReviewStep3Form.inc.php
classes/submission/reviewer/form/ReviewerReviewStep3Form.inc.php
js/controllers/form/reviewer/ReviewerReviewStep3FormHandler.js
locale/en_US/reviewer.po
pages/reviewer/PKPReviewerHandler.inc.php
styles/form/form.less
templates/form/formButtons.tpl
templates/reviewer/review/reviewFormResponse.tpl
templates/reviewer/review/step3.tpl

Initial work for https://github.com/pkp/pkp-lib/issues/3698, not ready for merge yet.

Add save for review forms, initial work

---

locale/en_US/common.po
templates/frontend/components/header.tpl

From issue: https://github.com/pkp/pkp-lib/issues/5240

#5240 Moved skip links to first child in header

---

templates/frontend/components/header.tpl

As per @israelcefrin's comments.

pkp/pkp-lib#5175 Moved h1 before journal logo

---

templates/common/userDetails.tpl
templates/frontend/components/registrationForm.tpl
templates/frontend/pages/userLostPassword.tpl
templates/user/contactForm.tpl

Change input type from text to email

---

templates/frontend/components/registrationForm.tpl
templates/frontend/pages/userLogin.tpl
templates/frontend/pages/userLostPassword.tpl

From this issue to address @israelcefrin's change: https://github.com/pkp/pkp-lib/issues/5186

pkp/pkp-lib#5186 Added aria-hidden to * spans

---

templates/frontend/pages/submissions.tpl

For this issue: https://github.com/pkp/pkp-lib/issues/5191#event-3299045066

Removed ::before and replaced with <span>

---

templates/submission/submissionMetadataFormFields.tpl

(cherry picked from commit ae88cf82ad47692e18c5ae6f1898893228b1b4e3)

[pkp-lib][3.2.0] #5796 Re-order section titles and descriptions for submissionMetadataFormFields

---

classes/notification/PKPNotificationOperationManager.inc.php
controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php

(cherry picked from commit 52660dc0265b3137ee26cab2a84c4894eb2c37e0)

[pkp-lib][3.2.0] #5095 Suppress stage assignment notification email, if the user email succeeds

---

classes/handler/PKPHandler.inc.php

https://github.com/pkp/pkp-lib/issues/5784

Move getTargetContext to pkp-lib

---

templates/frontend/pages/contact.tpl

Very important to reduce the number of spam by removing the exposure.
Native "Smarty" feature: https://www.smarty.net/docs/en/tips.obfuscating.email.tpl

Obfuscating email addresses

---

controllers/statistics/form/PKPReportGeneratorForm.inc.php

(cherry picked from commit 2889df0888f884b64a27858cb72255add85d3940)

[pkp-lib][3.2.1] #6029 Fix Day/Month Dimensions in statistics

---

api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php
api/v1/submissions/PKPSubmissionHandler.inc.php
classes/services/PKPSubmissionService.inc.php
classes/services/queryBuilders/PKPSubmissionQueryBuilder.inc.php
pages/dashboard/DashboardHandler.inc.php

For this issue: https://github.com/pkp/pkp-lib/issues/5982

pkp/pkp-lib#5982 Filtered editors to admins and managers only

---

pages/authorDashboard/PKPAuthorDashboardHandler.inc.php

Signed-off-by: JhonathanMiranda <jhon@lepidus.com.br>

pkp/pkp-lib#6056 Changes author dashboard handler so it sends publication version number

---

classes/migration/NavigationMenusMigration.inc.php
classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php
classes/navigationMenu/NavigationMenuItem.inc.php
classes/navigationMenu/NavigationMenuItemDAO.inc.php
classes/services/PKPNavigationMenuService.inc.php
controllers/grid/navigationMenus/form/PKPNavigationMenuItemsForm.inc.php
templates/controllers/grid/navigationMenus/remoteUrlNMIType.tpl

For this issue: https://github.com/pkp/pkp-lib/issues/6098

#6098 support multilingual remoteurl

---

classes/components/listPanels/PKPSubmissionsListPanel.inc.php
pages/dashboard/DashboardHandler.inc.php

For this issue: https://github.com/pkp/pkp-lib/issues/6054

pkp/pkp-lib#6054 Added Issues filter to Active submissions list panel

---

api/v1/_uploadPublicFile/PKPUploadPublicFileHandler.inc.php
classes/file/FileManager.inc.php

Just a couple of minor changes. One removes a PHP notice which I found distracting when trying to identify a problem by watching the error log. The other is an unused variable.

Stable 3 2 1

---

classes/form/FormBuilderVocabulary.inc.php

Remove redundancy of statements

Remove redundancy

---

templates/frontend/components/registrationForm.tpl

For this issue: https://github.com/pkp/pkp-lib/issues/5185

pkp/pkp-lib#5185 Added autocomplete to given and family name fields

---

classes/mail/Mail.inc.php

Explained in detail in the issue #6298

Issue: #6298: Temporary fix to configure SMTPSecure but without SMTPAuth

---

classes/submission/reviewRound/ReviewRound.inc.php
controllers/tab/authorDashboard/AuthorDashboardReviewRoundTabHandler.inc.php
locale/en_US/submission.po
pages/authorDashboard/PKPAuthorDashboardHandler.inc.php

This commit also fixes the notification request that was broken
during the UI refactor in #5865.

pkp/pkp-lib#6234 Make overdue reviews notice clearer for authors

---

classes/components/forms/FormComponent.inc.php

removeField() was not working properly, and I had to re-index the fields.
Thanks
Salman Murad

Fix removing field issue

---

classes/navigationMenu/NavigationMenuItemDAO.inc.php

Hi @NateWr @asmecher,
I have noticed this bug and made the changes to fix.
Please merge if it is ok.
Thanks
Salman

pkp/pkp-lib#6516 Fix remove navigation item

---

api/v1/submissions/PKPSubmissionFileHandler.inc.php
locale/en_US/api.po

Restores locale keys removed in https://github.com/pkp/pkp-lib/commit/50391bfe2915d1f7a620fc46ab297b1e76cf0893\#diff-cf438054f827419632df838470fe2bd8050c822674dd59b4d27f84b62a3638dc

pkp/pkp-lib#6574 Restore locale keys removed by accident

---

pages/libraryFiles/LibraryFileHandler.inc.php

pkp#6473: Library Files public url operates inline

---

pages/libraryFiles/LibraryFileHandler.inc.php

#6473: Library Files public url operates inline

---

classes/notification/PKPNotificationOperationManager.inc.php
classes/notification/managerDelegate/EditorialReportNotificationManager.inc.php

Resolves #6644 for master.  Suitable to cherry pick across stable 3.1 and 3.2.

#6644: Editorial Report Notification can be optional

---

classes/core/APIRouter.inc.php
classes/core/PKPComponentRouter.inc.php
classes/core/PKPPageRouter.inc.php
classes/core/PKPRouter.inc.php
classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php
locale/en_US/api.po

Fixing the branch name, allowing Travis to run properly

[5390] Adding better API responses in case of non api_secret_key filled, missing api token and invalid token

---

classes/form/validation/FormValidatorReCaptcha.inc.php
classes/template/PKPTemplateManager.inc.php
classes/user/form/RegistrationForm.inc.php
locale/en_US/common.po
pages/login/LoginHandler.inc.php
templates/frontend/pages/userLogin.tpl
templates/frontend/pages/userRegister.tpl

Hi!
Just refactored a bit the validator and added extra error messages.
I've also removed the `classes/webservice` folder. As I've ended up there and didn't find references to it anywhere (the code also has a broken reference).

Closes pkp/pkp-lib#6539 Extended reCaptcha to the login page.

---

templates/frontend/components/registrationForm.tpl
templates/frontend/pages/userLogin.tpl
templates/frontend/pages/userLostPassword.tpl

Added autocomplete attributes to login/register

---

classes/citation/CitationDAO.inc.php
classes/publication/PKPPublicationDAO.inc.php
classes/services/PKPPublicationService.inc.php
classes/submission/PKPSubmissionDAO.inc.php

port changes to the stable branch... for the next release...

pkp/pkp-lib#6071 Merge pull request #6159 from defstat/i6071

---

classes/components/listPanels/PKPSubmissionsListPanel.inc.php
pages/dashboard/DashboardHandler.inc.php

Hi @NateWr,
Please review the changes and let me know if any issues.
Thanks
Salman

pkp/pkp-lib#6809 Add submissions filter by category

---

controllers/grid/settings/user/form/UserDetailsForm.inc.php
pages/user/RegistrationHandler.inc.php
tests/config/config.TEMPLATE.mysql.inc.php
tests/config/config.TEMPLATE.pgsql.inc.php

#6994: remove obsolete implicit_auth setting

---

classes/validation/ValidatorORCID.inc.php
templates/common/userDetails.tpl
templates/user/publicProfileForm.tpl

Backport  changes from  https://github.com/pkp/pkp-lib/pull/7010

When using the sandbox API, the ORCID validator can't validate

---

classes/validation/ValidatorORCID.inc.php

Restrict orcid ids to only http

[pkp-lib] #7010 Rervert partially

---

classes/validation/ValidatorFactory.inc.php

Support only https in orcid ids

[pkp-lib] #7034  Revert  http support in ORCiD  ids

---

classes/migration/upgrade/PKPv3_4_0UpgradeMigration.inc.php

https://github.com/pkp/pkp-lib/issues/6685#issuecomment-895527198

pkp/pkp-lib#6685 Drop unused submission_tombstones table

---

controllers/grid/queries/form/QueryForm.inc.php

https://github.com/pkp/pkp-lib/issues/7277

pkp/pkp-lib#7277 Do not include declined open reviewers to author discussions

---

tools/plugins.php

Cleanup for 951c5c4 in  #7204.

pkp#7204: PSR-12 whitespace and doc cleanup of plugins CLI tool

---

tools/pluginGallery.php
tools/plugins.php

Initial tool for #7204 for 3.1.2 and 3.2.

#7204: Simple CLI tool to interact with Plugin Gallery

---

tools/pluginGallery.php
tools/plugins.php

Plugin gallery cli 3.2.1

---

classes/publication/PKPPublication.inc.php

the function getTitles() should return the locales as keys, like in getFullTitles()

return value of getTitles()

---

classes/submission/Collector.inc.php

s. https://github.com/pkp/pkp-lib/issues/7419

pkp/pkp-lib#7419 Fix ordering submissions by title

---

classes/components/forms/publication/PKPTitleAbstractForm.inc.php

Added publication object to PKPTitleAbstractForm based on https://github.com/pkp/pkp-lib/issues/7681

#7681 Added publication object to PKPTitleAbstractForm

---

classes/navigationMenu/NavigationMenuItemDAO.inc.php

issue pkp/pkp-lib#7651 fix for `main` branch .

pkp/pkp-lib#7651 Fatal error when trying to load PKPXMLParser

---

pages/user/RegistrationHandler.inc.php

aims to resolve issue pkp/pkp-lib#7880 .

pkp/pkp-lib#7880 Registration process throwing unhandled exception for new user registration

---

pages/user/RegistrationHandler.inc.php

This aims to solve the issue pkp/pkp-lib#7881 for the `stable-3_3_0` branch only .

pkp/pkp-lib#7881 User verification process failing with internal exception

---

classes/plugins/PluginGalleryDAO.inc.php
classes/site/Version.inc.php
composer.json
composer.lock

Original PR for stable-3_3_0: https://github.com/pkp/pkp-lib/pull/7809
These are just the changes made to stable-3_3_0 that were forward ported to main.
OJS [main] testing: https://github.com/pkp/ojs/pull/3377
OMP [main] testing: https://github.com/pkp/omp/pull/1107
OPS [main] testing: https://github.com/pkp/ops/pull/272

pkp/pkp-lib#7793 Changed main to use Composer's Semver 

---

classes/db/DAO.inc.php
classes/reviewForm/ReviewFormElementDAO.inc.php

This PR aims to solve pkp/pkp-lib#7909 .

pkp/pkp-lib#7909 Can not accept a submission if associated review has any review form attached to it

---

classes/file/PKPLibraryFileManager.inc.php
controllers/grid/settings/library/form/EditLibraryFileForm.inc.php
templates/controllers/grid/settings/library/form/editFileForm.tpl

Fixes for pkp/pkp-lib#5780 for 3.3.0.

pkp#5780: Draft replacement of Publisher Library file

---

js/controllers/UploaderHandler.js
templates/controllers/fileUploadContainer.tpl

This PR aims to resolve issue pkp/pkp-lib#7187 .

pkp/pkp-lib#7187 Drag and Drop fails on dependent files

---

classes/submissionFile/Repository.inc.php

This PR aims to fix pkp/pkp-lib#7937

pkp/pkp-lib#7937 Deleting dependent file cause submission activity log view to break

---

templates/controllers/grid/gridCellContents.tpl

This PR aims to fix pkp/pkp-lib#7954

pkp/pkp-lib#7954 Can not add options for optional type fields in the review form

---

classes/context/Context.inc.php
controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php

This PR aims to fix pkp/pkp-lib#7949

pkp/pkp-lib#7949 Can not add new item under checklist

---

classes/services/PKPUserService.inc.php

This PR aims to fix the issue pkp/pkp-lib#8055

pkp/pkp-lib#8055 Update the initialization of DAOResultFactory with sql and bindings params

---

classes/migration/install/CommonMigration.inc.php
classes/migration/upgrade/v3_4_0/I8060_UpdateUserLocalesDefaultToEmptyArrayFromNull.inc.php

This PR aims to provide a solution for pkp/pkp-lib#8060.

pkp/pkp-lib#8060 User locales column default updated to empty array

---

api/v1/dois/PKPDoiHandler.php
classes/components/listPanels/PKPDoiListPanel.php
classes/doi/Repository.php
classes/doi/exceptions/DoiActionException.php
classes/submission/Repository.php
cypress/support/commands.js
locale/en_US/manager.po
locale/en_US/submission.po

Expand error messaging and make DOI exception generic

pkp/pkp-lib#7518 Expand DOI bulk actions

---

classes/observers/traits/UsageEvent.php

s. https://github.com/pkp/pkp-lib/issues/8123

pkp/pkp-lib#8123 fix request property initialization in UsageEvent trait

---

templates/frontend/pages/userLogin.tpl
templates/frontend/pages/userLostPassword.tpl
templates/frontend/pages/userRegister.tpl

This PR is related to the issue https://github.com/pkp/pkp-lib/issues/5194 and fixes the following forms:
- Login
- Lost password
- Register

pkp/pkp-lib#5194 Add role="form" to all forms in default theme

---

classes/migration/install/AnnouncementsMigration.php
classes/migration/install/CategoriesMigration.php
classes/migration/install/CommonMigration.php
classes/migration/install/ControlledVocabMigration.php
classes/migration/install/DoiMigration.php
classes/migration/install/GenresMigration.php
classes/migration/install/LibraryFilesMigration.php
classes/migration/install/LogMigration.php
classes/migration/install/MetadataMigration.php
classes/migration/install/NavigationMenusMigration.php
classes/migration/install/ReviewFormsMigration.php
classes/migration/install/RolesAndUserGroupsMigration.php
classes/migration/install/SubmissionFilesMigration.php
classes/migration/install/SubmissionsMigration.php
classes/migration/install/TombstoneMigration.php
classes/migration/upgrade/v3_4_0/PKPI7014_DoiMigration.php

https://forum.pkp.sfu.ca/t/change-table-publication-settings-setting-value-datatype-from-text-to-mediumtext/73916
pkp/ojs:
classes/migration/install/OJSMigration.inc.php
pkp/pkp-lib:
lib/pkp/classes/migration/install/AnnouncementsMigration.inc.php
lib/pkp/classes/migration/install/CategoriesMigration.inc.php
lib/pkp/classes/migration/install/CommonMigration.inc.php
lib/pkp/classes/migration/install/ControlledVocabMigration.inc.php
lib/pkp/classes/migration/install/DoiMigration.inc.php
lib/pkp/classes/migration/install/GenresMigration.inc.php
lib/pkp/classes/migration/install/LibraryFilesMigration.inc.php
lib/pkp/classes/migration/install/LogMigration.inc.php
lib/pkp/classes/migration/install/MetadataMigration.inc.php
lib/pkp/classes/migration/install/NavigationMenusMigration.inc.php …

Change tables ..._settings > setting_value datatype from TEXT to MEDIUMTEXT

---

classes/author/Author.php
classes/identity/Identity.php

s. https://github.com/pkp/pkp-lib/issues/7546

pkp/pkp-lib#7546 fix getLocalizedGivenName and getLocalizedFamilyName

---

js/controllers/form/FormHandler.js
js/controllers/grid/users/stageParticipant/form/AddParticipantFormHandler.js
templates/controllers/grid/users/userSelect/searchUserFilter.tpl

https://github.com/pkp/pkp-lib/issues/7894

pkp/pkp-lib#7894 Recommend-only option disappears when looking for editors to assign

---

api/v1/_dois/PKPBackendDoiHandler.php
api/v1/_email/PKPEmailHandler.php
api/v1/_library/PKPLibraryHandler.php
api/v1/_payments/PKPBackendPaymentsSettingsHandler.php
api/v1/_submissions/PKPBackendSubmissionsHandler.php
api/v1/_uploadPublicFile/PKPUploadPublicFileHandler.php
api/v1/announcements/PKPAnnouncementHandler.php
api/v1/contexts/PKPContextHandler.php
api/v1/dois/PKPDoiHandler.php
api/v1/emailTemplates/PKPEmailTemplateHandler.php
api/v1/institutions/PKPInstitutionHandler.php
api/v1/mailables/MailableHandler.php
api/v1/site/PKPSiteHandler.php
api/v1/stats/contexts/PKPStatsContextHandler.php
api/v1/stats/editorial/PKPStatsEditorialHandler.php
api/v1/stats/publications/PKPStatsPublicationHandler.php
api/v1/stats/sushi/PKPStatsSushiHandler.php
api/v1/stats/users/PKPStatsUserHandler.php
api/v1/submissions/PKPSubmissionFileHandler.php
api/v1/submissions/PKPSubmissionHandler.php
api/v1/temporaryFiles/PKPTemporaryFilesHandler.php
api/v1/users/PKPUserHandler.php
api/v1/vocabs/PKPVocabHandler.php
classes/components/forms/context/PKPContextStatisticsForm.php
classes/components/forms/site/PKPSiteStatisticsForm.php
classes/handler/PKPHandler.php
locale/en_US/manager.po
pages/management/ManagementHandler.php
schemas/context.json
schemas/site.json

s. https://github.com/pkp/pkp-lib/issues/6781
This implements the general possibility for APIs to be public and the opt-out for public SISHI API as discussed in the issue.

pkp/pkp-lib#6781 Opt-out for public SUSHI API 

---

classes/components/forms/context/PKPContextStatisticsForm.php
classes/components/forms/site/PKPSiteStatisticsForm.php
classes/services/PKPSiteService.php
classes/statistics/PKPStatisticsHelper.php
locale/bg_BG/admin.po
locale/bg_BG/manager.po
locale/cs_CZ/admin.po
locale/cs_CZ/manager.po
locale/da_DK/admin.po
locale/da_DK/manager.po
locale/en_US/admin.po
locale/en_US/manager.po
locale/hy_AM/admin.po
locale/hy_AM/manager.po
locale/pt_BR/admin.po
locale/pt_BR/manager.po
locale/sl_SI/admin.po
locale/sl_SI/manager.po
locale/sv_SE/admin.po
locale/sv_SE/manager.po
pages/management/ManagementHandler.php

s. https://github.com/pkp/pkp-lib/issues/8250

pkp/pkp-lib#8250 Improve help text in statistics settings forms 

---

controllers/grid/users/reviewer/form/ResendRequestReviewerForm.php

This PR aims to solve pkp/pkp-lib#8311

pkp/pkp-lib#8311 ResendRequestReviewerForm missing abstract method added

---

classes/author/Repository.php
locale/en_US/common.po
schemas/author.json

This PR aims to solve pkp/pkp-lib#8344

pkp/pkp-lib#8344 Added country validation for contributor api

---

api/v1/contexts/PKPContextHandler.php
classes/components/forms/context/PKPContextForm.php
classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php
classes/services/PKPContextService.php
controllers/grid/admin/context/ContextGridHandler.php
schemas/context.json

This PR aims to solve pkp/pkp-lib#8183

pkp/pkp-lib#8183 Context contact name and email required at creation with preflight check

---

api/v1/stats/publications/PKPStatsPublicationHandler.php
classes/services/PKPStatsGeoService.php
classes/services/PKPStatsPublicationService.php
classes/services/queryBuilders/PKPStatsGeoQueryBuilder.php
classes/services/queryBuilders/PKPStatsPublicationQueryBuilder.php

s. https://github.com/pkp/pkp-lib/issues/7318

consider app specific stats API params

---

classes/migration/upgrade/v3_4_0/I7245_UpdateUserLocaleStringToParsableJsonString.php

This PR aims to solve pkp/pkp-lib#7245

pkp/pkp-lib#7245 Migration added to update colon separated user locales

---

tools/convertUsageStatsLogFile.php

s. https://github.com/pkp/pkp-lib/issues/6849

pkp/pkp-lib#6849 convert usage stats log file CLI tool

---

schemas/context.json
schemas/site.json
schemas/submission.json
schemas/user.json

This PR aims to solve pkp/pkp-lib#8327

pkp/pkp-lib#8327 Locale regex validation rules update to support 2 character locale code

---

classes/task/DepositDois.php
classes/task/EditorialReminders.php
classes/task/RemoveUnvalidatedExpiredUsers.php

This PR aims to solve pkp/pkp-lib#8374

pkp/pkp-lib#8374 Missing bool return tasks updated

---

api/v1/stats/contexts/PKPStatsContextHandler.php
classes/components/PKPStatsContextPage.php
classes/services/PKPStatsPublicationService.php
classes/template/PKPTemplateManager.php
locale/en_US/manager.po
pages/stats/PKPStatsHandler.php
templates/stats/context.tpl

s. https://github.com/pkp/pkp-lib/issues/7318

pkp/pkp-lib#7318 Stats Context Page

---

locale/ar_IQ/admin.po
locale/bg_BG/admin.po
locale/cs_CZ/admin.po
locale/da_DK/admin.po
locale/en_US/admin.po
locale/it_IT/admin.po
locale/pt_BR/admin.po
locale/pt_PT/admin.po
locale/sl_SI/admin.po

remove dot at the end of a locale key string

---

classes/statistics/PKPTemporaryItemInvestigationsDAO.php
classes/statistics/PKPTemporaryItemRequestsDAO.php
classes/statistics/PKPTemporaryTotalsDAO.php

s. https://github.com/pkp/pkp-lib/issues/8484

pkp/pkp-lib#8484 fix mariaDB delete queries

---

classes/publication/DAO.php
classes/publication/Repository.php

s. https://github.com/pkp/pkp-lib/issues/8530

pkp/pkp-lib#8530 Fix a bug when saving the references

---

classes/form/Form.inc.php
classes/form/FormBuilderVocabulary.inc.php
classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php
controllers/wizard/fileUpload/FileUploadWizardHandler.inc.php
controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php
templates/controllers/wizard/fileUpload/form/submissionFileMetadataForm.tpl
templates/form/textInput.tpl

This PR aims to solve pkp/pkp-lib#7369

pkp/pkp-lib#7369 Multilingual text input field required validation

---

controllers/grid/queries/form/QueryForm.inc.php

This PR aims to solve pkp/pkp-lib#7836

pkp/pkp-lib#7836 Updated condition to display possible list to associate with discussion

---

tools/travis/prepare-tests.sh

s. https://github.com/pkp/pkp-lib/issues/8490

pkp/pkp-lib#8490 consider mariaDB in Travis

---

classes/context/Context.php
classes/facades/Locale.php
classes/i18n/Locale.php
classes/i18n/LocaleMetadata.php
classes/site/Site.php
controllers/grid/languages/form/InstallLanguageForm.php
pages/management/ManagementHandler.php

This PR introduce update/patch for pkp/pkp-lib#7352

pkp/pkp-lib#7352 Locale presentation update

---

classes/services/queryBuilders/PKPContextQueryBuilder.php

This PR aims to provide solution for pkp/pkp-lib#8602

pkp/pkp-lib#8602 Query update to get distinct contexts only

---

classes/cliTool/MergeUsersTool.php

I've been studying the usage of this tool and noticed and fixed some inconsistencies in information text.

Fixes for usage information text

---

classes/user/UserStageAssignmentDAO.inc.php

This PR aims to provide solution for pkp/pkp-lib#8697

pkp/pkp-lib#8697 Fixed user assignment case insensitive search for postgres

---

classes/user/form/ContactForm.php

This PR aims to provide solution for pkp/pkp-lib#8715

pkp/pkp-lib#8715 Fixed user email update validation process

---

classes/components/forms/publication/Details.php

pkp/pkp-lib#8716 Reflect keywords requirement in submission details page

---

classes/section/Repository.php

pkp/pkp-lib#8750 Section empty logic update

---

classes/i18n/Locale.php
classes/install/form/InstallForm.php

pkp/pkp-lib#7352 Locale::getFormattedDisplayNames update to deduce locale code with @ char

---

classes/context/SubEditorsDAO.php
classes/migration/install/SubmissionsMigration.php
classes/migration/upgrade/v3_4_0/I8737_SectionEditorsUniqueIndexUpdate.php
controllers/grid/settings/category/form/CategoryForm.php
controllers/grid/settings/sections/form/PKPSectionForm.php
templates/controllers/grid/settings/category/form/categoryForm.tpl

This PR aims to provide solution for or pkp/pkp-lib#8737.

pkp/pkp-lib#8737 Section form multiple role associated user association fix

---

api/v1/_email/PKPEmailHandler.php
classes/core/PKPQueueDatabaseConnector.php
classes/core/PKPQueueProvider.php
classes/job/repositories/Job.php
jobs/bulk/BulkEmailSender.php
locale/en/manager.po
pages/management/ManagementHandler.php
templates/management/access.tpl

pkp/pkp-lib#8734 Added bulk mail sending job class and optimized bulk mail sending

---

api/v1/stats/editorial/PKPStatsEditorialHandler.php
api/v1/stats/publications/PKPStatsPublicationHandler.php
api/v1/stats/sushi/PKPStatsSushiHandler.php
classes/components/forms/site/PKPSiteStatisticsForm.php
classes/sushi/CounterR5Report.php
schemas/site.json

s. https://github.com/pkp/pkp-lib/issues/8851

pkp/pkp-lib#8851 fixes for stats, sections, institutions

---

classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php

This PR aims to provide solution for pkp/pkp-lib#8966

pkp/pkp-lib#8966 Preflight check submission checklist valid json check updated

---

classes/decision/types/BackFromCopyediting.php
classes/decision/types/CancelReviewRound.php
classes/submissionFile/Repository.php

This PR aims to provide solution for pkp/pkp-lib#8948

pkp/pkp-lib#8948 Fixed activity log on review cancel

---

classes/plugins/ImportExportPlugin.php

s. https://github.com/pkp/pkp-lib/issues/8962

pkp/pkp-lib#8962 possibility for importexport plugins not to support CLI

---

classes/plugins/PKPPubIdPlugin.inc.php

s. https://github.com/pkp/pkp-lib/issues/6293

pkp/pkp-lib#6293 fix checkDuplicate in PKPPubIdPlugin

---

classes/cliTool/traits/ConvertLogFile.php

s. https://github.com/pkp/pkp-lib/issues/9016

pkp/pkp-lib#9016 Fix ConvertLogFile after path_info_disabled cleanup

---

classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.inc.php

s. https://github.com/pkp/pkp-lib/commit/96883fad1a05f57615e59a360fdf927d4d2c1735#r123426775

pkp/pkp-lib#9132 use Capsule::raw

---

classes/mail/mailables/ReviewerRegister.php
classes/mail/mailables/UserCreated.php
controllers/grid/settings/user/form/UserDetailsForm.php
controllers/grid/users/reviewer/form/CreateReviewerForm.php
plugins/importexport/users/filter/UserXmlPKPUserFilter.php

pkp/pkp-lib#9227 Corrent password value in user registration email

---

classes/core/PKPApplication.php
classes/install/PKPInstall.php
classes/migration/upgrade/v3_4_0/I9136_MigrateUniqueSiteId.php
classes/site/Site.php
classes/site/VersionCheck.php
plugins/generic/usageEvent/PKPUsageEventPlugin.php
plugins/generic/usageEvent/settings.xml
schemas/site.json

s. https://github.com/pkp/pkp-lib/issues/9136

pkp/pkp-lib#9136 introduce new and migrate old uniqueSiteId

---

api/v1/submissions/PKPSubmissionHandler.php
classes/author/Author.php
classes/identity/Identity.php
plugins/metadata/dc11/schema/PKPDc11Schema.php

s. https://github.com/pkp/pkp-lib/issues/9184

pkp/pkp-lib#9184 fix getFullName, make dc:creator multilingual

---

classes/core/PKPContainer.php
jobs/BaseJob.php
jobs/bulk/BulkEmailSender.php
jobs/email/EditorialReminder.php
jobs/submissions/UpdateSubmissionSearchJob.php
jobs/testJobs/TestJobFailure.php
jobs/testJobs/TestJobSuccess.php
tools/jobs.php

pkp/pkp-lib#9195 Added queue jobs control configs

---

classes/author/Author.php
classes/core/DataObject.php
classes/identity/Identity.php
classes/publication/PKPPublication.php
classes/submission/PKPSubmission.php
classes/submissionFile/SubmissionFile.php

pkp/pkp-lib#8025 Centralized method getLocalizedData with updated locale precedence implementation

---

classes/security/Validation.php

s. https://github.com/pkp/pkp-lib/issues/9298

pkp/pkp-lib#9298 fix return type for Validation::loggedInAs

---

classes/cache/MemcacheCache.php

For me this solved the issue. 
I'm new to PHP, so I don't know if this is the right way to do this.

pkp#9323 Add use Memcached to MemcacheCache.php

---

classes/security/Validation.php
classes/user/form/BaseProfileForm.php
classes/user/form/ContactForm.php
pages/login/LoginHandler.php
templates/frontend/pages/userLogin.tpl

This PR aims to provide solution for pkp/pkp-lib#8871

pkp/pkp-lib#8871 Added login via email along with username

---

controllers/grid/settings/user/UserGridHandler.php

- Go to Settings, User and Roles
- Roles are displayed in the user list for each user

pkp/pkp-lib#9382 Display a role column in the user list

---

classes/core/PKPApplication.inc.php
templates/stats/publications.tpl

s. https://github.com/pkp/pkp-lib/issues/9397

pkp/pkp-lib#9397 Allow strict RFC compliant redirects for Guzzle

---

classes/template/PKPTemplateManager.php

s. https://github.com/pkp/pkp-lib/issues/9401

pkp/pkp-lib#9401 Fix inline styles added to htmlGalley context

---

classes/core/PKPApplication.php

s. https://github.com/pkp/pkp-lib/issues/9397

pkp/pkp-lib#9397 Allow strict RFC compliant redirects for Guzzle and pkp/pkp-lib#9401 Fix inline styles added to htmlGalley context 

---

templates/submission/form/categories.tpl

pkp/pkp-lib#9450 fixed issue when no category/section selected at submission time

---

classes/components/forms/dashboard/SubmissionFilters.php
js/load.js
pages/dashboard/DashboardHandlerNext.php
templates/layouts/backend.tpl
tools/i18nExtractKeys.vite.js

pkp/pkp-lib#7495 Adjust form to remove save button, extract translation strings also from stores/composables
pkp/pkp-lib#7495 Adjust actions column to be visible
pkp/pkp-lib#7495 Clean up

pkp/pkp-lib#7495 Submission Listing WIP

---

classes/section/PKPSection.php

s. https://github.com/pkp/pkp-lib/issues/9557

pkp/pkp-lib#9557 PKPSection::getTitle() can return null

---

classes/file/PKPLibraryFileManager.php
controllers/grid/settings/library/form/EditLibraryFileForm.php
templates/controllers/grid/settings/library/form/editFileForm.tpl

Publisher Library can swap files

---

api/v1/submissions/PKPSubmissionHandler.php

Previously a SlimRequest without body got errors.

#9604 Allow SlimRequest with no payload to edit the submission

---

classes/migration/upgrade/v3_4_0/I9627_AddUsageStatsTemporaryTablesIndexes.php
classes/observers/listeners/LogUsageEvent.php
classes/statistics/PKPStatisticsHelper.php
classes/statistics/PKPTemporaryItemInvestigationsDAO.php
classes/statistics/PKPTemporaryItemRequestsDAO.php
classes/statistics/PKPTemporaryTotalsDAO.php

s. https://github.com/pkp/pkp-lib/issues/9627

pkp/pkp-lib#9627 Add indexes to usage stats temporary tables

---

api/v1/stats/sushi/PKPStatsSushiHandler.php
classes/components/forms/counter/PKPCounterReportForm.php
classes/components/listPanels/PKPCounterReportsListPanel.php
classes/core/APIResponse.php
classes/services/queryBuilders/PKPStatsSushiQueryBuilder.php
classes/sushi/CounterR5Report.php
classes/template/PKPTemplateManager.php
locale/en/manager.po
pages/stats/PKPStatsHandler.php
templates/stats/counterReports.tpl

s. https://github.com/pkp/pkp-lib/issues/8248

pkp/pkp-lib#8248 COUNTER R5 TSV reports

---

api/v1/emailTemplates/PKPEmailTemplateController.php
api/v1/mailables/PKPMailableController.php

pkp/pkp-lib#9718 fixed mailables and emailTemplates route issue

---

classes/mail/Mailer.php
locale/en/common.po

pkp/pkp-lib#9296 Sandbox settings

---

classes/cliTool/ScheduledTaskTool.php
classes/core/PKPContainer.php
classes/core/PKPQueueProvider.php
classes/mail/Mailer.php
locale/en/admin.po
tools/jobs.php

patch for pkp/pkp-lib#9296 to handle cases in https://docs.pkp.sfu.ca/admin-guide/en/deploy-sandbox

pkp/pkp-lib#9296 Sandbox settings to handle steps from sandboxing doc

---

classes/site/VersionCheck.php

This is necessary to avoid Fatal Error if server has no internet connection.
#9767

#9767 Check if new version exists only if show_upgrade_warning is activated

---

classes/migration/install/RolesAndUserGroupsMigration.php
classes/migration/upgrade/v3_5_0/I9462_UserUserGroupsStartEndDate.php
classes/migration/upgrade/v3_5_0/I9709_UserUserGroupsMasthead.php
classes/user/Collector.php
classes/user/form/RegistrationForm.php
classes/userGroup/Repository.php
classes/userGroup/relationships/UserUserGroup.php
classes/userGroup/relationships/enums/UserUserGroupMastheadStatus.php
controllers/grid/settings/user/form/UserForm.php

s. https://github.com/pkp/pkp-lib/issues/9709

pkp/pkp-lib#9709 add masthead column to user_user_groups table

---

locale/fr_FR/submission.po

Added six strings not used in later versions and therefore not available for translation in Weblate.

Added missing strings in Weblate

---

templates/submission/review-contributors.tpl
templates/submission/review-details.tpl
templates/submission/review-editors.tpl
templates/submission/review-files.tpl
templates/submission/saved.tpl

Fix submission templates docs

---

classes/core/PKPPageRouter.php

Show locale in url in multilingual contexts

---

classes/citation/CitationListTokenizerFilter.inc.php
tests/classes/citation/CitationListTokenizerFilterTest.php

s. https://github.com/pkp/pkp-lib/issues/9946
s. https://github.com/pkp/pkp-lib/pull/9980

 Do not remove numbers from the beginning of each citation:

---

classes/security/authorization/internal/SubmissionCompletePolicy.inc.php
locale/en_US/user.po
pages/workflow/PKPWorkflowHandler.inc.php

pkp/pkp-lib#9837 Policy to restrict incomplete submission to access workflow

---

classes/site/VersionCheck.php

Changes exception handling to capture TransferException.

---

classes/core/PKPHtmlSanitizer.php
classes/core/PKPString.php

pkp/pkp-lib#7916 Added core PKPHtmlSanitizer class

---

classes/author/Repository.php

Hello
With this little change, we can give the possibility to change Author object before insert...
Thank you

Move Hook call before insert

---

classes/context/ContextDAO.inc.php
classes/services/PKPContextService.inc.php

pkp/pkp-lib/issues/9191 Fix Context seq ordering

---

controllers/grid/settings/user/form/UserDetailsForm.php

pkp/pkp-lib#10065 fixed issue of updating own password form users & roles section

---

classes/mail/Mailable.php

pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject

---

controllers/grid/users/author/AuthorGridHandler.inc.php
controllers/grid/users/author/form/PKPAuthorForm.inc.php

fixes issue [#10019](https://github.com/pkp/pkp-lib/issues/10019)

pkp/pkp-lib#10019 Activity Log not updating when modifying contributor

---

classes/log/EmailLogDAO.php
classes/migration/install/LogMigration.php

Fix pkp/pkp-lib/10020 - Long publication title stops submit/review process

---

controllers/grid/users/author/AuthorGridHandler.php
controllers/grid/users/author/form/PKPAuthorForm.php

s. https://github.com/pkp/pkp-lib/issues/10019
only submodule udpate

pkp/pkp-lib#10019 Fix publication update when modifying contributor

---

dtd/userGroups.dtd

s. https://github.com/pkp/pkp-lib/issues/9552

pkp/pkp-lib#9552 add masthead attribute to the userGroups.dtd

---

classes/components/forms/FormComponent.php
styles/form/form.less
templates/form/formButtons.tpl

Closes https://github.com/pkp/pkp-lib/issues/10001

pkp/pkp-lib#10001 Possibility to add Cancel button in the form

---

classes/user/DAO.php

pkp/pkp-lib#10017 Handle duplicate entries in user settings when changing site primary locale

---

classes/services/queryBuilders/PKPStatsPublicationQueryBuilder.php

Fixes #1009
Fixes ambiguous column reference.

pkp-lib#10098 fix ambiguous column reference in query

---

api/v1/stats/contexts/PKPStatsContextController.php
api/v1/stats/publications/PKPStatsPublicationController.php
classes/core/PKPRoutingProvider.php

s. https://github.com/pkp/pkp-lib/issues/10145

pkp/pkp-lib#10145 consider TSV as API response

---

classes/components/forms/context/PKPAppearanceMastheadForm.php
classes/components/forms/context/PKPMastheadForm.php
classes/submission/reviewAssignment/DAO.php
classes/submission/reviewAssignment/Repository.php
locale/en/manager.po
pages/about/AboutContextHandler.php

s. https://github.com/pkp/pkp-lib/issues/10080

pkp/pkp-lib#10080 Consider only external reviewers for display on Editorial Masthead page

---

classes/stageAssignment/StageAssignment.php

pkp#10220 Use eloquence HasCamelCasing trait in StageAssignment model

---

controllers/grid/plugins/PluginGalleryGridHandler.inc.php

Adds Guzzle exception handling in PluginGalleryGridHandler

---

classes/notification/NotificationDAO.php

For https://github.com/pkp/pkp-lib/issues/9987

pkp#9987 fix issue when marking notification as unread

---

classes/config/Config.php

hide provider's secrets in admin page

---

classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php

s. https://github.com/pkp/pkp-lib/issues/10244

pkp/pkp-lib#10244 Consider no usage stats log files in preflight check

---

classes/core/APIRouter.php
classes/core/Dispatcher.php
classes/core/PKPBaseController.php
classes/core/PKPRequest.php
classes/core/PKPRouter.php
classes/core/PKPRoutingProvider.php
classes/handler/APIHandler.php
locale/en/api.po

pkp/pkp-lib#9434 Allow plugin level API call

---

classes/middleware/HasRoles.php

pkp#10266 update HasRoles middleware to apply admin role for site wide admins

---

classes/middleware/ValidateCsrfToken.php

for https://github.com/pkp/pkp-lib/issues/10279

pkp#10279 fix incorrect check for API Token

---

classes/submission/DAO.php

For https://github.com/pkp/pkp-lib/issues/10303

add missing Notification class import

---

classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php
templates/submission/form/categories.tpl

pkp#6055 Bug fix: address missing category selection after failed submission form validation

---

controllers/grid/files/form/LibraryFileForm.php
controllers/grid/settings/library/form/EditLibraryFileForm.php

For https://github.com/pkp/pkp-lib/issues/10287

PKP#10287 fix types

---

classes/user/form/IdentityForm.php
classes/user/form/PublicProfileForm.php
templates/user/identityForm.tpl
templates/user/publicProfileForm.tpl

For https://github.com/pkp/pkp-lib/issues/10315

pkp/pkp-lib#10315 Move ORCID connect button to user Identity tab

---

cypress/support/commands.js
locale/en/api.po

s. https://github.com/pkp/pkp-lib/issues/9468

pkp/pkp-lib#9468 add api.dois.403.editItemDoiCantBeAssigned key

---

classes/author/Repository.php
classes/orcid/OrcidManager.php
classes/user/form/IdentityForm.php
controllers/tab/user/ProfileTabHandler.php
jobs/orcid/RevokeOrcidToken.php
templates/form/orcidProfile.tpl
templates/user/identityForm.tpl

pkp/pkp-lib#10318 Revoke ORCID tokens when deleting authenticated ORCIDs

---

classes/orcid/OrcidManager.php

For https://github.com/pkp/pkp-lib/issues/10344

pkp/pkp-lib#10344 fix import in OrcidManager

---

classes/middleware/DecodeApiTokenWithValidation.php
classes/middleware/ValidateCsrfToken.php
classes/middleware/traits/HasRequiredMiddleware.php

pkp/pkp-lib#10342 Required depending middleware attachment check

---

api/v1/submissions/PKPSubmissionController.php
locale/en/api.po
pages/workflow/PKPWorkflowHandler.php

For https://github.com/pkp/pkp-lib/issues/10336

pkp/pkp-lib#10336 Expose publication forms via API

---

controllers/grid/queries/QueriesGridHandler.php

resolve new discussion error refs pkp/pkp-lib#10385

---

api/v1/orcid/OrcidController.php
classes/orcid/actions/VerifyAuthorWithOrcid.php
schemas/author.json

For https://github.com/pkp/pkp-lib/issues/10389

pkp/pkp-lib#10389 Track author Orcid verification request state

---

classes/migration/upgrade/v3_5_0/I9425_SeparateUIAndSubmissionLocales.php

pkp/pkp-lib#10293 Null data preservation on locale related column update

---

api/v1/submissions/PKPSubmissionController.php
classes/decision/Collector.php

pkp/pkp-lib#10465 Improve GET submissions/{submissionId}/decisions endpoint

---

classes/identity/Identity.inc.php
classes/submission/PKPAuthor.inc.php

Back-porting changes made in https://github.com/pkp/pkp-lib/commit/37b2762d820a0be45c412e34a4b897f4a999e1da

pkp/pkp-lib#10046 Use default locale for user full name when passed

---

jobs/email/EditorialReminder.php

Editorial Reminder: miscalculation for inactiveDays pkp#10376

---

api/v1/submissions/PKPSubmissionController.php

pkp/pkp-lib#10481 allow assistant role to access GET /participants endpoints for submissions

---

api/v1/submissions/PKPSubmissionController.php

pkp/pkp-lib#10508 Apply getLocalizedForm method to TitleAbstractForm form

---

controllers/grid/users/reviewer/form/ResendRequestReviewerForm.php
controllers/grid/users/reviewer/form/ReviewerForm.php
controllers/grid/users/reviewer/form/ReviewerNotifyActionForm.php
controllers/grid/users/reviewer/form/traits/HasReviewDueDate.php
templates/controllers/grid/users/reviewer/form/resendRequestReviewerForm.tpl

for pkp/pkp-lib#4789 . see more details at https://github.com/pkp/pkp-lib/issues/4789#issuecomment-2014034378

pkp/pkp-lib#4789 Due date fields added for declined review request resending

---

tests/jobs/email/ReviewReminderTest.php

pkp/pkp-lib#10517 added skip for ReviewReminder job test for OPS

---

classes/user/maps/Schema.php

Extend the usr API to support  group start date.
e.g. "dateStart": "2024-10-11 05:25:10" under  groups
```json
{
"_href": "http://localhost:8000/index.php/publicknowledge/api/v1/users/18",
"affiliation": {
"en": "University of Bologna",
"fr_CA": ""
},
"apiKey": null,
"apiKeyEnabled": null,
"authStr": null,
"billingAddress": null,
"biography": {
"en": "",
"fr_CA": ""
},
"country": "IT",
"dateLastEmail": null,
"dateLastLogin": "2024-10-11 05:25:08",
"dateRegistered": "2024-10-11 05:25:08",
"dateValidated": null,
"disabled": false,
"disabledReason": null,
"email": "ccorino@mailinator.com",
"familyName": {
"en": "Corino",
"fr_CA": ""
},
"fullName": "Carlo Corino",
"givenName": {
"en": "Carlo",
"fr_CA": ""
},
"groups": [
{
"id": 14,
"name": {
"en": "Author",
"fr_CA": "Auteur-e"
},
"abbrev": { …
```

Add Group Start Date to groups API

---

api/v1/stats/sushi/PKPStatsSushiController.php
classes/components/forms/counter/PKPCounterReportForm.php
classes/components/listPanels/PKPCounterReportsListPanel.php
classes/services/queryBuilders/PKPStatsSushiQueryBuilder.php
classes/sushi/CounterR5Report.php
classes/template/PKPTemplateManager.php
locale/en/manager.po
pages/stats/PKPStatsHandler.php
templates/stats/counterReports.tpl

s. https://github.com/pkp/pkp-lib/issues/9666

pkp/pkp-lib#9666 COUNTER R5 TSV reports 

---

locale/en/common.po
templates/frontend/pages/editorialHistory.tpl
templates/frontend/pages/editorialMasthead.tpl

s. https://github.com/pkp/pkp-lib/issues/10392

pkp/pkp-lib#10392 Masthead styling

---

classes/submission/maps/Schema.php
schemas/submission.json

pkp/pkp-lib#10537 Add available editorial decisions to submission's stages data

---

cypress/support/commands_new_workflow.js

Cypess integration tests for user invitation workflow
#9658

Create user invitation

---

locale/en/invitation.po

see https://github.com/craft-oa/gdpr-invitation/issues/71 and https://github.com/craft-oa/gdpr-invitation/issues/68

craft-oa/gdpr-invitation#71 add accept invitation cancel popup text changes

---

classes/announcement/Announcement.php
classes/core/EntityDAO.php
classes/core/SettingsBuilder.php
classes/core/traits/EntityUpdate.php
classes/services/PKPSchemaService.php

pkp/pkp-lib#10292 Fix update setting values for a Model

---

api/v1/reviews/PKPReviewController.php
classes/core/PKPString.php
composer.json
composer.lock
locale/en/api.po
locale/en/editor.po
templates/controllers/grid/users/reviewer/readReview.tpl
templates/controllers/grid/users/reviewer/reviewDownload.tpl

https://github.com/pkp/pkp-lib/issues/9873

Download reviews from modal

---

classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php

pkp/pkp-lib#10546 Fix Confirm/Declined text displayed in reviewer history

---

classes/identity/Identity.php
classes/user/form/IdentityForm.php
locale/en/user.po
schemas/user.json
templates/user/identityForm.tpl

pkp/pkp-lib#10489 Allow users to add custom initials for avatars

---

classes/category/Collector.php
classes/category/DAO.php
classes/publication/DAO.php
classes/publication/PublicationCategory.php
classes/publication/Repository.php
classes/submission/Collector.php
schemas/publication.json

pkp/pkp-lib#10158 Move categoryids out of of publication_settings

---

classes/invitation/invitations/userRoleAssignment/handlers/UserRoleAssignmentInviteRedirectController.php
cypress/support/commands_new_workflow.js
pages/invitation/InvitationHandler.php

- https://github.com/pkp/pkp-lib/issues/9658
-

#9658 user invitation

---

.gitignore

s. https://github.com/pkp/pkp-lib/issues/10712

pkp/pkp-lib#10712 add weblate language.json to .gitignore

---

api/v1/_submissions/PKPBackendSubmissionsController.php
api/v1/submissions/PKPSubmissionController.php
classes/submission/Collector.php
classes/submission/Repository.php
pages/dashboard/DashboardHandler.php

pkp/pkp-lib#6998 Don't allow mixed type for  query param

---

classes/identity/Identity.php
classes/submission/maps/Schema.php
classes/user/maps/Schema.php
schemas/user.json

pkp/pkp-lib#10651 Determine initials to be displayed for users

---

classes/migration/upgrade/v3_5_0/I10620_EditorialBoardMemberRole.php
locale/en/default.po
tests/classes/i18n/LocaleTest.php

s. https://github.com/pkp/pkp-lib/issues/10620

pkp/pkp-lib#10620 introduce new Editorial Board Member assistant role

---

locale/en/submission.po
pages/submission/PKPSubmissionHandler.php
templates/submission/cancelled.tpl
templates/submission/wizard.tpl

pkp/pkp-lib#8350 Allow authors to cancel submission

---

classes/submission/Collector.php

pkp/pkp-lib10662 Fix `isOverdue` query in submission filters

---

controllers/api/file/PKPManageFileApiHandler.php

pkp/pkp-lib#10705 Fix file upload cancellation issue

---

classes/components/forms/announcement/PKPAnnouncementForm.php
pages/management/ManagementHandler.php

Related to this issue: [https://github.com/pkp/pkp-lib/issues/10837#issuecomment-2608136349](https://github.com/pkp/pkp-lib/issues/10837#issuecomment-2608136349)

pkp#10837 ojs stable 3.4.0 Add image code and list to announcement desc toolbar

---

classes/core/traits/EntityUpdate.php

pkp/pkp-lib#10868 Fix settings table update

---

includes/functions.php

pkp/pkp-lib#10884 Only json_decode strings in PKPSchemaService::coerce()

---

classes/i18n/LocaleConversion.php
classes/template/PKPTemplateManager.php

s. https://github.com/pkp/pkp-lib/issues/10795

pkp/pkp-lib#10795 introduce LocaleConversion::toBcp47()

---

classes/payment/Payment.php

pkp/pkp-lib#10834 Added proper type hints to handle type conversions

---

controllers/grid/settings/roles/UserGroupGridHandler.php
controllers/grid/settings/roles/form/UserGroupForm.php

pkp/pkp-lib#10788 User group create/update/remove fix

---

classes/controlledVocab/ControlledVocabEntryMatch.php
classes/controlledVocab/Repository.php

pkp/pkp-lib#10948 Fixed case insensitive matching of vocabs

---

classes/core/traits/ModelWithSettings.php

pkp/pkp-lib#10690 Allow to fallback locale for localized data on eloquent model

---

api/v1/orcid/OrcidController.php
classes/author/maps/Schema.php
jobs/orcid/RevokeOrcidToken.php

Fixed ORCiD issues:

---

classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php
classes/migration/install/ReviewsMigration.php
classes/migration/upgrade/v3_5_0/I10359_DateConsideredToReviewAssignments.php
classes/migration/upgrade/v3_5_0/I10359_DateEditorConfirmedToReviewAssignments.php
classes/submission/maps/Schema.php
classes/submission/reviewAssignment/DAO.php
classes/submission/reviewAssignment/ReviewAssignment.php
controllers/grid/users/reviewer/form/ThankReviewerForm.php
schemas/reviewAssignment.json

pkp/pkp-lib#10359 Exposing date when editor confirmed review in API with dateEditorConfirmed

---

composer.json
composer.lock

pkp/pkp-lib#10973 Composer dependency update

---

classes/submissionFile/Repository.php

pkp/pkp-lib#10814 Log file deletion

---

pages/user/ProfileHandler.php

see issue https://github.com/pkp/pkp-lib/issues/11004

fix show profile activation date notification for new context

---

pages/user/ProfileHandler.php

see https://github.com/pkp/pkp-lib/issues/11004#issuecomment-2691466124

check context is empty when check the roles count

---

classes/log/Repository.php
classes/user/Repository.php

pkp/pkp-lib#10977 Fix issues within merge user functionality

---

classes/submission/maps/Schema.php
schemas/submission.json

pkp/pkp-lib#11024 Update API to include copyedit stage files count

---

controllers/grid/settings/user/form/UserForm.php

s. https://github.com/pkp/pkp-lib/issues/11078

pkp/pkp-lib#11078 consider context in UserForm::saveUserGroupAssignments

---

controllers/grid/users/userSelect/UserSelectGridCellProvider.php
controllers/grid/users/userSelect/UserSelectGridHandler.php

Hi,
Here is the PR for the `ojs-stable-3_5_0` branch related to the issue [#9999](https://github.com/pkp/pkp-lib/issues/9999)

pkp/pkp-lib#9999 OJS stable-3_5_0 Add affiliation and reviewing interests to participants grid

---

classes/submission/DashboardView.php
classes/submission/Repository.php
locale/en/submission.po

pkp/pkp-lib#10835 Update dashboard views (stable 3.5)

---

js/controllers/form/FormHandler.js

s. https://github.com/pkp/pkp-lib/issues/7165

pkp/pkp-lib#7165 Issue datePublished can be set when adding an issue

---

classes/scheduledTask/PKPScheduler.php

s. https://github.com/pkp/pkp-lib/issues/11145

pkp/pkp-lib#11145 UpdateIPGeoDB should be run on 10th every month

---

classes/submission/maps/Schema.php

For pkp/pkp-lib#11025 
tests - https://github.com/pkp/ojs/pull/4746

pkp/pkp-lib#11025 Include issue info on submission API data

---

templates/admin/index.tpl
templates/user/apiProfileForm.tpl

pkp/pkp-lib#11185 Fix button formatting issues [main]

---

templates/admin/index.tpl
templates/user/apiProfileForm.tpl

pkp/pkp-lib#11185 Fix button formatting issues [stable 3.5]

---

api/v1/invitations/InvitationController.php
classes/security/authorization/UserRolesRequiredPolicy.php
classes/user/maps/Schema.php
classes/userGroup/relationships/UserUserGroup.php
controllers/grid/settings/user/UserGridHandler.php
controllers/grid/users/author/AuthorGridRow.php
locale/en/user.po
pages/invitation/InvitationHandler.php

see https://github.com/pkp/pkp-lib/issues/11014 , https://github.com/pkp/pkp-lib/issues/11026 , https://github.com/pkp/pkp-lib/issues/11016

 fix issue in invitation,role base authorization and add permissions to invitation page

---

classes/migration/upgrade/v3_5_0/I10292_UpdateControlledVocabEntrySettingName.php

related to pkp/pkp-lib#11194 , see comment https://github.com/pkp/pkp-lib/issues/11194#issuecomment-2777486855 and more that follows from there .

pkp/pkp-lib#11194 update of setting_name only for default symbolics

---

locale/en/editor.po

pkp/pkp-lib#11190 Restore mistakenly removed translation

---

api/v1/submissions/PKPSubmissionController.php
controllers/wizard/fileUpload/form/SubmissionFilesMetadataForm.php

s. https://github.com/pkp/pkp-lib/issues/11251

pkp/pkp-lib#11251 fix change submission locale for files and affiliation names, and determination of submission locale in SubmissionFilesMetadataForm

---

api/v1/invitations/InvitationController.php
classes/security/authorization/UserRolesRequiredPolicy.php
classes/user/maps/Schema.php
classes/userGroup/relationships/UserUserGroup.php
controllers/grid/settings/user/UserGridHandler.php
controllers/grid/users/author/AuthorGridRow.php
locale/en/user.po
pages/invitation/InvitationHandler.php

https://github.com/pkp/pkp-lib/pull/11216

fix issue in invitation,role base authorization and add permissions to invitation page

---

js/usage-stats-chart.js

s. https://github.com/pkp/pkp-lib/issues/11212

pkp/pkp-lib#11212 chart.js y-axis beginAtZero

---

classes/citation/CitationDAO.php
classes/core/PKPApplication.php
classes/migration/install/MetadataMigration.php
classes/migration/upgrade/v3_5_0/I11238_PrepareDBForStructuredCitations.php
classes/publication/DAO.php
classes/publication/maps/Schema.php
plugins/importexport/native/filter/PKPPublicationNativeXmlFilter.php
schemas/publication.json
tools/parseCitations.php

s. https://github.com/pkp/pkp-lib/issues/11238
and 
https://github.com/pkp/pkp-lib/issues/10629

pkp/pkp-lib#11238 prepare DB for structured citations

---

classes/submission/reviewRound/ReviewRound.php
jobs/email/EditorialReminder.php

pkp/pkp-lib#10214 Editorial reminder issue update

---

tests/jobs/email/EditorialReminderTest.php

pkp/pkp-lib#11298 Added missing user mock for EditorialReminderTest

---

cypress/support/command_reviewer_suggestion.js

pkp/pkp-lib#10993 Reviewer Suggestion E2E test

---

api/v1/submissions/PKPSubmissionController.php
classes/author/Repository.php
classes/galley/Repository.php
classes/security/authorization/internal/RepresentationUploadAccessPolicy.php
classes/submission/Repository.php
classes/task/PublishSubmissions.php
controllers/grid/users/author/AuthorGridHandler.php
locale/en/submission.po

for [issue##10263](https://github.com/pkp/pkp-lib/issues/10263)

pkp/pkp-lib#10263 Relax editing metadata on published/posted materials

---

js/controllers/grid/users/stageParticipant/form/StageParticipantNotifyHandler.js

This PR is for this issue: [11236](https://github.com/pkp/pkp-lib/issues/11236)

pkp/pkp-lib#11236 OJS stable-3_3_0 Fix assignment privileges not working correctly

---

js/controllers/grid/users/reviewer/AdvancedReviewerSearchHandler.js

to resolve https://github.com/pkp/pkp-lib/issues/4787#issuecomment-2848460630 .

pkp/pkp-lib#4787 removed window dependencey to get global jQuery in legacy JS

---

classes/core/PKPApplication.php
classes/submission/Representation.php
classes/submission/RepresentationDAOInterface.php

s. https://github.com/pkp/pkp-lib/issues/11260

pkp/pkp-lib#11260 fix return type in getRepresentationDao()

---

classes/install/Installer.php

s. https://github.com/pkp/pkp-lib/issues/11363

pkp/pkp-lib#11363 run UpdateIPGeoDB on install and upgrade

---

classes/handler/APIHandler.php

pkp/pkp-lib#11356 Apply default API controller middleware to routes from plugin

---

classes/submission/reviewer/form/PKPReviewerReviewStep3Form.php
js/controllers/form/reviewer/ReviewerReviewStep3FormHandler.js

pkp/pkp-lib#11390 Allow nullable reviewer recommendation at save for later

---

controllers/grid/settings/user/UserGridHandler.php
locale/en/invitation.po

see https://github.com/pkp/pkp-lib/issues/11265

add legacy add user for sys admin

---

classes/submission/Repository.php

for [#10263](https://github.com/pkp/pkp-lib/issues/10263)

pkp/pkp-lib#10263 Follow-up to clean up canEditPublication method per review feedback from PR#11225

---

classes/migration/upgrade/v3_5_0/InstallEmailTemplates.php

for [issue#9202](https://github.com/pkp/pkp-lib/issues/9202)

pkp/pkp-lib#9202 Include 3.4 missing email templates in 3.5 upgrade

---

classes/invitation/invitations/userRoleAssignment/handlers/UserRoleAssignmentInviteUIController.php

https://github.com/pkp/pkp-lib/issues/11118#issuecomment-2814704882

handle user not found in edit user

---

classes/user/form/RolesForm.php
pages/submission/PKPSubmissionHandler.php

https://github.com/pkp/pkp-lib/issues/11319

fix edit profile role removeing reset user permission

---

classes/submission/reviewer/form/PKPReviewerReviewStep3Form.inc.php

Add a Hook for PKPReviewerReviewStep3Form::saveForLater() for stable_3_3_0

---

classes/submission/reviewer/form/PKPReviewerReviewStep3Form.php

Add a Hook for PKPReviewerReviewStep3Form::saveForLater() for main

---

api/v1/submissions/PKPSubmissionController.php
classes/components/forms/submission/StartSubmission.php
pages/submission/PKPSubmissionHandler.php

pkp/pkp-lib#10929 Temporary fix - implement app level SubmissionHandler::getSubmitUserGroups [main]

---

classes/migration/upgrade/v3_5_0/I11125_UpdateEmailTemplateVariables.php

pkp/pkp-lib#11125 Fix: Copyediting Stage, Discussion tags do not populate [stable3.5]

---

classes/invitation/stepTypes/SendInvitationStep.php
controllers/grid/settings/user/form/UserForm.php
controllers/grid/users/reviewer/form/CreateReviewerForm.php
controllers/grid/users/reviewer/form/EnrollExistingReviewerForm.php
templates/controllers/grid/settings/user/form/userDetailsForm.tpl
templates/controllers/grid/users/reviewer/form/createReviewerForm.tpl
templates/controllers/grid/users/reviewer/form/enrollExistingReviewerForm.tpl

s. https://github.com/pkp/pkp-lib/issues/11437

pkp/pkp-lib#11437 Reviewers are always displayed on masthead

---

classes/invitation/core/Invitation.php
classes/invitation/invitations/userRoleAssignment/handlers/api/UserRoleAssignmentReceiveController.php
classes/invitation/invitations/userRoleAssignment/payload/UserRoleAssignmentInvitePayload.php
classes/user/Collector.php
locale/en/userAccess.po

pkp/pkp-lib#11474 Allow search by role in Users & Roles search (stable3.5)

---

cypress/support/commands.js
cypress/tests/integration/Categories.cy.js

pkp/pkp-lib#11411 Update category tests

---

controllers/grid/settings/languages/SubmissionLanguageGridHandler.php

see https://github.com/pkp/pkp-lib/issues/11536

pkp/pkp-lib#11536 Remove gridrow actions from the Submission Languages Grid

---

classes/components/forms/highlight/HighlightForm.php

pkp/pkp-lib#11333 Use FieldRichTextarea for Highlights form description field (main)

---

classes/components/forms/highlight/HighlightForm.php

pkp/pkp-lib#11333 Use FieldRichTextarea for HighlightForm description field (stable3.5)

---

classes/observers/listeners/AssignEditors.php

Fix subscription check for editor assignment email notification

---

locale/en/submission.po
templates/submission/review-reviewer-suggestions.tpl

pkp/pkp-lib#11517 Remove suggestion reason for suggested reviewer in submission wizard(main)

---

classes/migration/upgrade/v3_5_0/I11603_AddMissingUserRoleAssignmentInvitationEmail.php
classes/migration/upgrade/v3_5_0/InstallEmailTemplates.php

pkp/pkp-lib#11603 Missing email temaple for role assignment invitation

---

.gitmodules
classes/author/Author.php
classes/author/DAO.php
classes/author/creditContributorRole/CreditContributorRole.php
classes/author/creditContributorRole/Repository.php
classes/author/creditRole/CreditRole.php
classes/author/creditRole/CreditRoleDegree.php
classes/author/creditRole/Repository.php
classes/author/maps/Schema.php
classes/components/forms/FieldCreditRoles.php
classes/components/forms/publication/ContributorForm.php
classes/facades/Repo.php
classes/migration/install/SubmissionsMigration.php
classes/migration/upgrade/v3_6_0/I857_CreditRoles.php
locale/en/submission.po
schemas/author.json

s. https://github.com/pkp/pkp-lib/issues/857
and 
https://github.com/pkp/pkp-lib/pull/11507

pkp/pkp-lib#857 Credit Roles

---

classes/invitation/invitations/userRoleAssignment/helpers/UserGroupHelper.php
classes/invitation/invitations/userRoleAssignment/resources/BaseUserRoleAssignmentInviteResource.php

pkp/pkp-lib#11671 Add date sanity checks in invitation flow (#11672)

---

classes/handler/APIHandler.php
classes/middleware/PolicyAuthorizer.php
classes/plugins/interfaces/HasAuthorizationPolicy.php

pkp/pkp-lib#11631 Ability to inject policies in api route from plugin

---

classes/migration/upgrade/v3_5_0/I11673_AddMissingApprovalToReviewerSuggestion.php
classes/submission/reviewer/suggestion/ReviewerSuggestion.php

pkp/pkp-lib#11673 Fix reviewer sugeestion resolve submission in multi context env

---

api/v1/submissions/PKPSubmissionController.php
classes/author/Repository.php

for [#11389](https://github.com/pkp/pkp-lib/issues/11389)

pkp/pkp-lib#11389 Add validation to ensure userGroupId belongs to an author group when adding/editing contributor

---

api/v1/comments/resources/UserCommentResource.php

pkp/pkp-lib#11770 Fix issue where public comments are not shown to unauthenticated user

---

classes/task/ReviewReminder.php

pkp/pkp-lib#11772 fixed carbon 3.x diffIn* method negative value issue

---

classes/mail/Mailer.php

This pull request introduces updates to the `Mailer` class in `classes/mail/Mailer.php` to improve DMARC compliance and ensure compatibility with both `Illuminate\Mail\Message` and `Symfony\Component\Mime\Email`. The key changes include enforcing DMARC-compliant "From" headers, adding support for Symfony's `Address` class, and refactoring methods to handle both message types uniformly.
* Added a call to `setDmarcCompliantFrom` in `sendSymfonyMessage` to ensure the "From" header is rewritten before sending, enforcing DMARC compliance.
* Refactored `setDmarcCompliantFrom` to accept both `Illuminate\Mail\Message` and `Symfony\Component\Mime\Email`, ensuring flexibility and compatibility.
* Updated `promoteFromToReplyTo` to uniformly extract and handle "Reply-To" and "From" addresses for both …

fix(email): correctly respect DMARC-compliant From header settings

---

classes/filter/FilterDAO.php
classes/publication/DAO.php
classes/publication/PKPPublication.php
classes/publication/Repository.php
locale/en/grid.po

s. https://github.com/pkp/pkp-lib/issues/11589
The new introduces function getMinorVersionsSettingValues() is used in the DOAJ plugin.

pkp/pkp-lib#11589 Consider JAV versions for indexing

---

api/v1/submissions/tasks/resources/TaskResource.php
classes/editorialTask/EditorialTask.php

pkp/pkp-lib#11910 Add name of the user started the task to the API
